import React from 'react';
import { addItr3PartAQDRow, readItr3PartAQD, removeItr3PartAQDRow, updateItr3PartAQD, type ITR3PartAQDRow } from '../domain/itr3PartAQD';
import type { ITR3BusinessWorkspace } from '../domain/returns/types';

interface Props { workspace: ITR3BusinessWorkspace; onChange: (workspace: ITR3BusinessWorkspace) => void; }
const branches: readonly ['TradingConcern' | 'RawMaterial' | 'FinishrByProd', string][] = [['TradingConcern','Trading concern'],['RawMaterial','Raw materials'],['FinishrByProd','Finished products / by-products']];
const fields: readonly (keyof ITR3PartAQDRow)[] = ['ItemName','UnitOfMeasure','OpeningStock','PurchaseQty','SaleQty','ClgStock','AnyShortExces','PrevYrConsum','yldFinisProd','PercentYld','PrevyrManfact'];
const numeric = new Set<keyof ITR3PartAQDRow>(fields.slice(2));
function listFor(data: ReturnType<typeof readItr3PartAQD>, branch: string): ITR3PartAQDRow[] { return branch === 'TradingConcern' ? data.TradingConcern ?? [] : branch === 'RawMaterial' ? data.ManfactrConcern?.RawMaterial ?? [] : data.ManfactrConcern?.FinishrByProd ?? []; }
/** Dedicated official PARTA_QD editor; only scalar source facts are editable. */
export default function ITR3PartAQDEditor({ workspace, onChange }: Props): React.JSX.Element {
  const data = readItr3PartAQD(workspace);
  const change = (branch: 'TradingConcern' | 'RawMaterial' | 'FinishrByProd', index: number, field: keyof ITR3PartAQDRow, value: string): void => onChange(updateItr3PartAQD(workspace, branch, index, field, value));
  return <section aria-label="PARTA_QD dedicated editor"><h3>Part A-QD — Quantitative details</h3><p>Enter source quantities only. The official QuantitDet arrays and all JSON nesting are serialized by the backend. A manufacturing concern (raw materials + finished products) must have at least one row in <em>both</em> branches, or neither.</p>{branches.map(([branch, label]) => { const list = listFor(data, branch); return <div key={branch} style={{ marginBottom: 16, padding: 12, border: '1px solid var(--border)', borderRadius: 6 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><h4 style={{ margin: 0 }}>{label}</h4><button type="button" disabled={list.length >= 20} onClick={() => onChange(addItr3PartAQDRow(workspace, branch))}>+ Add row</button></div>{list.map((item, index) => <div key={index} style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginTop: 10, marginBottom: 10 }}>{fields.map((field) => <label key={field}><span>{String(field)}</span><input aria-label={`${branch} ${index + 1} ${String(field)}`} type={numeric.has(field) ? 'number' : 'text'} min={numeric.has(field) ? 0 : undefined} value={item[field] ?? ''} onChange={(event) => change(branch, index, field, event.target.value)} /></label>)}<button type="button" aria-label={`Remove ${branch} row ${index + 1}`} onClick={() => onChange(removeItr3PartAQDRow(workspace, branch, index))} style={{ alignSelf: 'end' }}>Remove</button></div>)}</div>; })}</section>;
}
