import React, { useEffect } from 'react';
import { BankAccountManager, type BankAccountData } from './BankAccountManager';
import { ITD_COUNTRY_CODES } from '../constants/itdCountryCodes';
import { STATE_CODE_OPTIONS, type StateCode } from '../domain/returns/cbdtEnums';
import { getDueDate, todayIso } from '../domain/returns/dueDates';
import type { ReturnDraft } from '../domain/returns/types';

interface Props {
  draft: ReturnDraft;
  onChange: (patch: DraftPatch) => void;
  onBanksChange: (data: BankAccountData) => void;
  onRegimeChange: (regime: 'old' | 'new') => void;
}

type DraftPatch = {
  personal?: Partial<ReturnDraft['personal']>;
  filing?: Partial<ReturnDraft['filing']>;
  verification?: Partial<ReturnDraft['verification']>;
  itr3AuditInfo?: Partial<ReturnDraft['itr3AuditInfo']>;
  itr3BalanceSheet?: Partial<ReturnDraft['itr3BalanceSheet']>;
  itr3NatureOfBusiness?: ReturnDraft['itr3NatureOfBusiness'];
  regime?: ReturnDraft['regime'];
};

type Address = {
  residenceNo: string;
  residenceName: string;
  roadOrStreet: string;
  localityOrArea: string;
  city: string;
  stateCode: string;
  countryCode: string;
  pinCode: string;
  zipCode: string;
};

const card: React.CSSProperties = { background: '#fff', border: '1px solid var(--border)', borderRadius: 8, padding: 16, marginBottom: 14 };
const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 };
const label: React.CSSProperties = { display: 'block', marginBottom: 4, fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)' };
const input: React.CSSProperties = { width: '100%', boxSizing: 'border-box', padding: '8px 10px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 13 };
const PAN = '[A-Z]{5}[0-9]{4}[A-Z]';
const PIN = '[1-9][0-9]{5}';

function Field({ label: text, value, onChange, type = 'text', required = false, pattern, maxLength, min, max, help }: { label: string; value: string | number | null | undefined; onChange: (value: string) => void; type?: React.HTMLInputTypeAttribute; required?: boolean; pattern?: string; maxLength?: number; min?: number; max?: number; help?: string }): React.JSX.Element {
  const id = `itr3-${text.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`;
  return <div><label htmlFor={id} style={label}>{text}{required && <span style={{ color: 'var(--danger)' }}> *</span>}</label><input id={id} style={input} value={value ?? ''} onChange={(event) => onChange(event.target.value)} type={type} required={required} pattern={pattern} maxLength={maxLength} min={min} max={max} />{help && <div style={{ marginTop: 4, color: 'var(--text-muted)', fontSize: 11 }}>{help}</div>}</div>;
}

function Select({ label: text, value, onChange, children, required = false }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode; required?: boolean }): React.JSX.Element {
  return <div><label style={label}>{text}{required && <span style={{ color: 'var(--danger)' }}> *</span>}</label><select style={input} value={value} onChange={(event) => onChange(event.target.value)} required={required}>{children}</select></div>;
}

function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }): React.JSX.Element {
  return <section style={card}><h3 style={{ margin: '0 0 4px', fontSize: 16, color: 'var(--text-primary)' }}>{title}</h3><p style={{ margin: '0 0 14px', fontSize: 12, lineHeight: 1.5, color: 'var(--text-muted)' }}>{description}</p>{children}</section>;
}

function addressFromPersonal(personal: ReturnDraft['personal']): Address {
  return { residenceNo: personal.flatNo, residenceName: personal.residenceName, roadOrStreet: personal.roadOrStreet, localityOrArea: personal.localityOrArea, city: personal.city, stateCode: personal.stateCode, countryCode: personal.countryCode || '91', pinCode: personal.pinCode, zipCode: personal.zipCode };
}

function addressFromAlternate(personal: ReturnDraft['personal']): Address {
  const address = personal.alternateAddress;
  return address ? { residenceNo: address.residenceNo, residenceName: address.residenceName, roadOrStreet: address.roadOrStreet, localityOrArea: address.localityOrArea, city: address.cityOrTownOrDistrict, stateCode: address.stateCode, countryCode: address.countryCode || '91', pinCode: address.pinCode, zipCode: address.zipCode } : { residenceNo: '', residenceName: '', roadOrStreet: '', localityOrArea: '', city: '', stateCode: '', countryCode: '91', pinCode: '', zipCode: '' };
}

function AddressFields({ prefix, value, onChange }: { prefix: string; value: Address; onChange: (key: keyof Address, value: string) => void }): React.JSX.Element {
  const india = value.countryCode === '91';
  return <div style={grid}>
    <Field label={`${prefix} flat / door / block no.`} value={value.residenceNo} onChange={(next) => onChange('residenceNo', next)} required maxLength={50} />
    <Field label={`${prefix} premises / building / village`} value={value.residenceName} onChange={(next) => onChange('residenceName', next)} maxLength={50} />
    <Field label={`${prefix} road / street / post office`} value={value.roadOrStreet} onChange={(next) => onChange('roadOrStreet', next)} maxLength={50} />
    <Field label={`${prefix} area / locality`} value={value.localityOrArea} onChange={(next) => onChange('localityOrArea', next)} required maxLength={50} />
    <Field label={`${prefix} town / city / district`} value={value.city} onChange={(next) => onChange('city', next)} required maxLength={50} />
    <Select label={`${prefix} country`} value={value.countryCode} onChange={(next) => onChange('countryCode', next)} required>{ITD_COUNTRY_CODES.map((country) => <option key={country.value} value={country.value}>{country.value} — {country.label}</option>)}</Select>
    <Select label={`${prefix} state`} value={value.stateCode} onChange={(next) => onChange('stateCode', next)} required><option value="">-- Select state --</option>{STATE_CODE_OPTIONS.filter(({ code }) => india ? code !== '99' : code === '99').map(({ code, label: stateLabel }) => <option key={code} value={code}>{code} — {stateLabel}</option>)}</Select>
    {india ? <Field label={`${prefix} PIN code`} value={value.pinCode} onChange={(next) => onChange('pinCode', next.replace(/\D/g, '').slice(0, 6))} required pattern={PIN} maxLength={6} /> : <Field label={`${prefix} ZIP / postal code`} value={value.zipCode} onChange={(next) => onChange('zipCode', next)} required maxLength={8} />}
  </div>;
}

/**
 * Tax-professional ITR-3 Personal Information page for AY 2026-27.
 *
 * This page is intentionally isolated from PersonalInfoTab so ITR-1, ITR-2,
 * and ITR-4 retain their existing UI and behavior.
 */
export function ITR3PersonalInfoPage({ draft, onChange, onBanksChange, onRegimeChange }: Props): React.JSX.Element {
  const { personal, filing, verification } = draft;
  const primary = addressFromPersonal(personal);
  const alternate = addressFromAlternate(personal);
  const updatePersonal = (patch: Partial<ReturnDraft['personal']>): void => onChange({ personal: patch });
  const updateFiling = (patch: Partial<ReturnDraft['filing']>): void => onChange({ filing: patch });
  const updateVerification = (patch: Partial<ReturnDraft['verification']>): void => onChange({ verification: patch });
  const updateAddress = (which: 'primary' | 'alternate', key: keyof Address, value: string): void => {
    const next = { ...(which === 'primary' ? primary : alternate), [key]: value };
    if (key === 'countryCode') next.stateCode = value === '91' && next.stateCode === '99' ? '' : value === '91' ? next.stateCode : '99';
    if (which === 'primary') updatePersonal({ flatNo: next.residenceNo, residenceName: next.residenceName, roadOrStreet: next.roadOrStreet, localityOrArea: next.localityOrArea, city: next.city, stateCode: next.stateCode as StateCode | '', countryCode: next.countryCode, pinCode: next.pinCode, zipCode: next.zipCode });
    else updatePersonal({ alternateAddress: { residenceNo: next.residenceNo, residenceName: next.residenceName, roadOrStreet: next.roadOrStreet, localityOrArea: next.localityOrArea, cityOrTownOrDistrict: next.city, stateCode: next.stateCode as StateCode | '', countryCode: next.countryCode, pinCode: next.pinCode, zipCode: next.zipCode } });
  };

  useEffect(() => {
    // Only auto-fill on first mount -- re-running this on every change to
    // verification.date would silently overwrite a date the preparer just
    // cleared intentionally.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    if (!verification.date) updateVerification({ date: todayIso() });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return <div>
    <div style={{ ...card, background: 'var(--gold-pale)' }}><strong style={{ color: 'var(--text-primary)' }}>ITR-3 · Part A — Personal Information</strong><div style={{ marginTop: 5, fontSize: 12, color: 'var(--text-muted)' }}>Complete this profile first. Your answers determine the filing-status, audit, business, and supporting schedules shown later.</div></div>
    <Section title="Assessee identity" description="Part A A1–A4 and A14–A16. These fields map to PartA_GEN1.PersonalInfo and are used throughout the return."><div style={grid}>
      <Field label="First name" value={personal.firstName} onChange={(value) => updatePersonal({ firstName: value, name: [value, personal.middleName, personal.surnameOrOrgName].filter(Boolean).join(' ') })} maxLength={25} />
      <Field label="Middle name" value={personal.middleName} onChange={(value) => updatePersonal({ middleName: value, name: [personal.firstName, value, personal.surnameOrOrgName].filter(Boolean).join(' ') })} maxLength={25} />
      <Field label="Surname / organisation name" value={personal.surnameOrOrgName} onChange={(value) => updatePersonal({ surnameOrOrgName: value, name: [personal.firstName, personal.middleName, value].filter(Boolean).join(' ') || value })} required maxLength={75} />
      <Field label="PAN" value={personal.pan} onChange={(value) => updatePersonal({ pan: value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10) })} required pattern={PAN} maxLength={10} help="Format: ABCDE1234F." />
      <Select label="Status" value={personal.assesseeStatus === 'H' ? 'H' : 'I'} onChange={(value) => updatePersonal({ assesseeStatus: value as 'I' | 'H' | 'F' })} required><option value="I">Individual</option><option value="H">HUF</option></Select>
      <Field label="Date of birth / formation" value={personal.dateOfBirth || ''} onChange={(value) => updatePersonal({ dateOfBirth: value || null })} type="date" required />
      <Field label="Father's name" value={personal.fatherName} onChange={(value) => updatePersonal({ fatherName: value })} required maxLength={125} help="Not a separate line item on the ITR-3 form itself — used to complete the Verification declaration ('I, [name], son/daughter of [father's name] ...')." />
      <Field label="Aadhaar number" value={personal.aadhaar} onChange={(value) => updatePersonal({ aadhaar: value.replace(/\D/g, '').slice(0, 12) })} pattern="[0-9]{12}" maxLength={12} />
    </div></Section>
    <Section title="Primary address" description="Part A A5a–A13a. The country controls whether the form requires an Indian PIN or foreign ZIP/postal code."><AddressFields prefix="Primary" value={primary} onChange={(key, value) => updateAddress('primary', key, value)} /></Section>
    <Section title="Communication details" description="Part A communication fields. Enter the taxpayer’s active mobile and email used for filing communication."><div style={grid}>
      <Field label="Mobile country code" value={personal.mobileCountryCode} onChange={(value) => updatePersonal({ mobileCountryCode: value.replace(/\D/g, '').slice(0, 5) })} required pattern="[0-9]{1,5}" maxLength={5} />
      <Field label="Mobile number" value={personal.mobile} onChange={(value) => updatePersonal({ mobile: value.replace(/\D/g, '').slice(0, 10) })} required pattern="[1-9][0-9]{4,9}" maxLength={10} />
      <Field label="Primary email" value={personal.email} onChange={(value) => updatePersonal({ email: value.trim() })} type="email" required maxLength={125} />
      <Field label="Secondary mobile country code" value={personal.secondaryMobileCountryCode} onChange={(value) => updatePersonal({ secondaryMobileCountryCode: value.replace(/\D/g, '').slice(0, 5) })} pattern="[0-9]{1,5}" maxLength={5} />
      <Field label="Secondary mobile number" value={personal.secondaryMobile} onChange={(value) => updatePersonal({ secondaryMobile: value.replace(/\D/g, '').slice(0, 10), secondaryMobileCountryCode: personal.secondaryMobileCountryCode || '91' })} pattern="[1-9][0-9]{4,9}" maxLength={10} />
      <Field label="Secondary email" value={personal.secondaryEmail} onChange={(value) => updatePersonal({ secondaryEmail: value.trim() })} type="email" maxLength={125} />
    </div></Section>
    <Section title="Secondary / alternate address" description="Part A secondary-address indicator and A5b–A13b. Select Yes only when a distinct correspondence address must be reported."><label style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 13 }}><input type="checkbox" checked={personal.secondaryAddressDifferent} onChange={(event) => updatePersonal({ secondaryAddressDifferent: event.target.checked, alternateAddress: event.target.checked ? (personal.alternateAddress ?? { residenceNo: '', residenceName: '', roadOrStreet: '', localityOrArea: '', cityOrTownOrDistrict: '', stateCode: '', countryCode: '91', pinCode: '', zipCode: '' }) : null })} />A different secondary address is applicable</label>{personal.secondaryAddressDifferent && <div style={{ marginTop: 14 }}><AddressFields prefix="Secondary" value={alternate} onChange={(key, value) => updateAddress('alternate', key, value)} /></div>}</Section>
    <Section title="Filing status and regime" description="Start with the return section and tax regime. Conditional notice, revised-return, and Form 10-IEA workflows will be expanded in the Filing Status phase."><div style={grid}>
      <Select label="Return filed under section" value={filing.filingSection} onChange={(value) => updateFiling({ filingSection: value as ReturnDraft['filing']['filingSection'], returnType: value === '139(5)' ? 'REVISED' : 'ORIGINAL' })} required><option value="139(1)">139(1) — On or before due date</option><option value="139(4)">139(4) — Belated</option><option value="139(5)">139(5) — Revised</option><option value="142(1)">142(1) — Notice</option><option value="148">148 — Reassessment notice</option><option value="153C">153C — Search/requisition assessment notice</option><option value="139(9)">139(9) — Defective return</option><option value="92CD">92CD — Modified return</option><option value="119(2)(b)">119(2)(b) — Condonation</option></Select>
      <Field label="ITR filing due date" value={getDueDate('ITR-3', draft.assessmentYear || '2026-27')} onChange={() => undefined} type="date" />
      <Select label="Tax regime election" value={draft.regime === 'old' ? 'old' : 'new'} onChange={(value) => { const regime = value as 'old' | 'new'; onChange({ regime }); onRegimeChange(regime); }} required><option value="new">New tax regime</option><option value="old">Old tax regime / opt out</option></Select>
      {filing.filingSection === '92CD' && <Field label="Date of advance pricing agreement" value={filing.form10IEADate || ''} onChange={(value) => updateFiling({ form10IEADate: value || null })} type="date" required help="Section 92CD modified return: date the APA was entered into." />}
      {['139(5)', '139(9)', '92CD'].includes(filing.filingSection) && <><Field label="Original acknowledgement number" value={filing.originalAcknowledgementNumber} onChange={(value) => updateFiling({ originalAcknowledgementNumber: value.replace(/\D/g, '').slice(0, 15) })} required pattern="[0-9]{15}" maxLength={15} /><Field label="Original return filing date" value={filing.originalFilingDate || ''} onChange={(value) => updateFiling({ originalFilingDate: value || null })} type="date" required /></>}
      {['142(1)', '148', '153C', '139(9)', '119(2)(b)'].includes(filing.filingSection) && <><Field label="Notice / order number" value={filing.noticeNumber} onChange={(value) => updateFiling({ noticeNumber: value })} required maxLength={100} /><Field label="Notice / order date" value={filing.noticeDate || ''} onChange={(value) => updateFiling({ noticeDate: value || null })} type="date" required /></>}
    </div></Section>
    <Section title="Form 10-IEA regime history — Part A A19(b)" description="The default regime under section 115BAC(1A) is the new regime; the old regime can only be chosen by filing Form 10-IEA on or before the due date under section 139(1). Answer only if the taxpayer has income from business or profession this year."><div style={{ display: 'grid', gap: 10 }}>
      <Select label="Have you filed ITR-3/4 and Form 10-IEA within due date for any earlier AY, choosing the old regime?" value={filing.form10IEAEarlierAYOldRegime} onChange={(value) => updateFiling({ form10IEAEarlierAYOldRegime: value as 'Y' | 'N' | 'NA' })}><option value="NA">Not applicable — no business/profession income this year</option><option value="N">No</option><option value="Y">Yes</option></Select>
      {filing.form10IEAEarlierAYOldRegime === 'Y' && <div style={{ display: 'grid', gap: 10 }}>
        <div style={grid}>
          <Select label="Assessment year of that earlier Form 10-IEA (old regime)" value={filing.form10IEAAssessmentYear} onChange={(value) => updateFiling({ form10IEAAssessmentYear: value as '' | '2024-25' | '2025-26' })} required><option value="">-- Select AY --</option><option value="2024-25">2024-25</option><option value="2025-26">2025-26</option></Select>
          <Field label="Form 10-IEA acknowledgement number (old regime)" value={filing.form10IEAEarlierAYAckOldRegime} onChange={(value) => updateFiling({ form10IEAEarlierAYAckOldRegime: value })} required maxLength={20} />
        </div>
        <Select label="Have you since re-entered the new regime by filing a later Form 10-IEA?" value={filing.form10IEAEarlierAYNewRegime} onChange={(value) => updateFiling({ form10IEAEarlierAYNewRegime: value as 'Y' | 'N' })} required><option value="N">No</option><option value="Y">Yes</option></Select>
        {filing.form10IEAEarlierAYNewRegime === 'Y' && <div style={grid}>
          <Select label="Assessment year of that later Form 10-IEA (new regime)" value={filing.form10IEANewRegimeAssessmentYear} onChange={(value) => updateFiling({ form10IEANewRegimeAssessmentYear: value as '' | '2025-26' })} required><option value="">-- Select AY --</option><option value="2025-26">2025-26</option></Select>
          <Field label="Form 10-IEA acknowledgement number (new regime)" value={filing.form10IEAEarlierAYAckNewRegime} onChange={(value) => updateFiling({ form10IEAEarlierAYAckNewRegime: value })} required maxLength={20} />
        </div>}
        {filing.form10IEAEarlierAYNewRegime === 'N' && <><label><input type="checkbox" checked={filing.form10IEACurrentAYNewRegime} onChange={(event) => updateFiling({ form10IEACurrentAYNewRegime: event.target.checked })} /> Furnishing Form 10-IEA now, to re-enter the new regime for the current AY</label>
        {filing.form10IEACurrentAYNewRegime && <div style={grid}>
          <Field label="Form 10-IEA date (current AY, re-entering new regime)" value={filing.form10IEACurrentAYNewRegimeDate || ''} onChange={(value) => updateFiling({ form10IEACurrentAYNewRegimeDate: value || null })} type="date" required />
          <Field label="Form 10-IEA acknowledgement number (current AY, new regime)" value={filing.form10IEACurrentAYNewRegimeAck} onChange={(value) => updateFiling({ form10IEACurrentAYNewRegimeAck: value })} required maxLength={20} />
        </div>}</>}
      </div>}
      {filing.form10IEAEarlierAYOldRegime === 'N' && <div style={{ display: 'grid', gap: 10 }}>
        <label><input type="checkbox" checked={filing.form10IEACurrentAYOldRegime} onChange={(event) => updateFiling({ form10IEACurrentAYOldRegime: event.target.checked })} /> Furnished Form 10-IEA within due date for the current AY, choosing the old regime</label>
        {filing.form10IEACurrentAYOldRegime && <div style={grid}>
          <Field label="Form 10-IEA date (current AY, old regime)" value={filing.form10IEACurrentAYOldRegimeDate || ''} onChange={(value) => updateFiling({ form10IEACurrentAYOldRegimeDate: value || null })} type="date" required />
          <Field label="Form 10-IEA acknowledgement number (current AY, old regime)" value={filing.form10IEACurrentAYOldRegimeAck} onChange={(value) => updateFiling({ form10IEACurrentAYOldRegimeAck: value })} required maxLength={20} />
        </div>}
      </div>}
      {filing.form10IEAEarlierAYOldRegime === 'NA' && <Select label="Do you wish to opt for the old regime for the current AY?" value={filing.optOldRegimeCurrAY} onChange={(value) => updateFiling({ optOldRegimeCurrAY: value as 'Y' | 'N' | '' })} required><option value="">-- Select --</option><option value="N">No</option><option value="Y">Yes</option></Select>}
    </div></Section>
    <Section title="Residential status and filing triggers" description="Part A filing-status disclosures. These answers control foreign-income, Schedule FSI/FA, and seventh-proviso applicability; answer every Yes/No question explicitly."><div style={grid}>
      <Select label="Residential status" value={personal.residentialStatus || 'ROR'} onChange={(value) => updatePersonal({ residentialStatus: value as ReturnDraft['personal']['residentialStatus'] })} required><option value="ROR">Resident and ordinarily resident</option><option value="RNOR">Resident but not ordinarily resident</option><option value="NR">Non-resident</option></Select>
      {personal.residentialStatus !== 'ROR' && <><Select label="Basis for residential status (Section 6)" value={filing.conditionsResStatus} onChange={(value) => updateFiling({ conditionsResStatus: value as ReturnDraft['filing']['conditionsResStatus'] })} required><option value="">-- Select basis --</option><option value="1">1 — 182 days or more in India this year [6(1)(a)]</option><option value="2">2 — 60+ days this year and 365+ days in preceding 4 years [6(1)(c)]</option><option value="3">3 — Non-resident in 9 of the preceding 10 years [6(6)(a)]</option><option value="4">4 — In India 729 days or less in preceding 7 years [6(6)(a)]</option><option value="5">5 — Non-resident during the previous year</option><option value="6">6 — Citizen/PIO visiting India, income &gt;₹15L, 120-181 days [6(6)(c)]</option><option value="7">7 — Citizen, income &gt;₹15L, not liable to tax elsewhere [6(6)(d)/6(1A)]</option><option value="8">8 — Citizen, crew member of Indian ship [Expl. 1(a) of 6(1)(c)]</option><option value="9">9 — Citizen/PIO visiting India [Expl. 1(b) of 6(1)(c)]</option></Select><Field label="Days in India — previous year" value={filing.totalStayIndiaPrevYr ?? ''} onChange={(value) => updateFiling({ totalStayIndiaPrevYr: value === '' ? null : Math.max(0, Math.min(365, Number(value) || 0)) })} type="number" min={0} max={365} /><Field label="Days in India — preceding 4 years" value={filing.totalStayIndia4PrecYr ?? ''} onChange={(value) => updateFiling({ totalStayIndia4PrecYr: value === '' ? null : Math.max(0, Math.min(1461, Number(value) || 0)) })} type="number" min={0} max={1461} /></>}
      {personal.residentialStatus !== 'NR' && <Select label="Section 115H benefit" value={filing.benefitUs115H ? 'Y' : 'N'} onChange={(value) => updateFiling({ benefitUs115H: value === 'Y', benefitUs115HAnswered: true })} required><option value="N">No</option><option value="Y">Yes</option></Select>}
      <Select label="FII / FPI status" value={filing.isFiiFpi ? 'Y' : 'N'} onChange={(value) => updateFiling({ isFiiFpi: value === 'Y' })} required><option value="N">No</option><option value="Y">Yes</option></Select>
      {filing.isFiiFpi && <Field label="SEBI registration number" value={filing.sebiRegistrationNumber} onChange={(value) => updateFiling({ sebiRegistrationNumber: value.toUpperCase().slice(0, 20) })} required maxLength={20} />}
      <Select label="Governed by Portuguese Civil Code (Section 5A)?" value={filing.portugueseCivilCodeApplies ? 'Y' : 'N'} onChange={(value) => updateFiling({ portugueseCivilCodeApplies: value === 'Y' })} required><option value="N">No</option><option value="Y">Yes</option></Select>
      {filing.portugueseCivilCodeApplies && <div style={{ fontSize: 11, color: 'var(--text-muted)', gridColumn: '1 / -1' }}>Schedule 5A (apportionment of income between spouses) must also be completed.</div>}
      <Field label="Legal Entity Identifier (LEI)" value={filing.leiNumber} onChange={(value) => updateFiling({ leiNumber: value.toUpperCase().slice(0, 20) })} maxLength={20} help="Mandatory only where refund claimed is ₹50 crore or more." />
      {filing.leiNumber && <Field label="LEI valid up to" value={filing.leiValidUptoDate || ''} onChange={(value) => updateFiling({ leiValidUptoDate: value || null })} type="date" />}
    </div>{personal.residentialStatus !== 'ROR' && <div style={{ marginTop: 14 }}><h4 style={{ margin: '0 0 8px', fontSize: 13 }}>Foreign residence jurisdictions</h4>{filing.jurisdictionResidenceEntries.map((row, index) => <div key={row.id} style={{ ...grid, marginBottom: 8 }}><Select label={`Jurisdiction ${index + 1} country`} value={row.jurisdictionCode} onChange={(value) => updateFiling({ jurisdictionResidenceEntries: filing.jurisdictionResidenceEntries.map((item) => item.id === row.id ? { ...item, jurisdictionCode: value } : item) })} required><option value="">-- Select country --</option>{ITD_COUNTRY_CODES.map((country) => <option key={country.value} value={country.value}>{country.value} — {country.label}</option>)}</Select><Field label={`Jurisdiction ${index + 1} TIN`} value={row.tin} onChange={(value) => updateFiling({ jurisdictionResidenceEntries: filing.jurisdictionResidenceEntries.map((item) => item.id === row.id ? { ...item, tin: value } : item) })} required maxLength={75} /><button type="button" onClick={() => updateFiling({ jurisdictionResidenceEntries: filing.jurisdictionResidenceEntries.filter((item) => item.id !== row.id) })}>Remove</button></div>)}<button type="button" onClick={() => updateFiling({ jurisdictionResidenceEntries: [...filing.jurisdictionResidenceEntries, { id: `itr3-jurisdiction-${Date.now()}`, jurisdictionCode: '', tin: '' }] })}>Add jurisdiction</button></div>}</Section>
    <Section title="Seventh proviso to section 139(1)" description="Part A A19(c). Only relevant for a taxpayer not otherwise required to file under section 139(1), filing solely because one of the conditions below applies."><div style={{ display: 'grid', gap: 10 }}>
      <label><input type="checkbox" checked={filing.seventhProvisoApplies} onChange={(event) => updateFiling({ seventhProvisoApplies: event.target.checked })} /> Filing under the seventh proviso to section 139(1) but otherwise not required to furnish a return</label>
    {filing.seventhProvisoApplies && <div style={{ display: 'grid', gap: 10, marginTop: 4 }}>
      <label><input type="checkbox" checked={filing.seventhProviso.depositExceedsOneCrore} onChange={(event) => updateFiling({ seventhProviso: { ...filing.seventhProviso, depositExceedsOneCrore: event.target.checked } })} /> Current-account deposits exceeded ₹1 crore</label>{filing.seventhProviso.depositExceedsOneCrore && <Field label="Aggregate current-account deposits (₹)" value={filing.seventhProviso.depositAmount} onChange={(value) => updateFiling({ seventhProviso: { ...filing.seventhProviso, depositAmount: Math.max(0, Number(value) || 0) } })} type="number" min={10000000} required />}
      <label><input type="checkbox" checked={filing.seventhProviso.foreignTravel} onChange={(event) => updateFiling({ seventhProviso: { ...filing.seventhProviso, foreignTravel: event.target.checked } })} /> Foreign-travel expenditure exceeded ₹2 lakh</label>{filing.seventhProviso.foreignTravel && <Field label="Foreign-travel expenditure (₹)" value={filing.seventhProviso.foreignTravelAmount} onChange={(value) => updateFiling({ seventhProviso: { ...filing.seventhProviso, foreignTravelAmount: Math.max(0, Number(value) || 0) } })} type="number" min={200000} required />}
      <label><input type="checkbox" checked={filing.seventhProviso.electricityExpenditure} onChange={(event) => updateFiling({ seventhProviso: { ...filing.seventhProviso, electricityExpenditure: event.target.checked } })} /> Electricity expenditure exceeded ₹1 lakh</label>{filing.seventhProviso.electricityExpenditure && <Field label="Electricity expenditure (₹)" value={filing.seventhProviso.electricityExpenditureAmount} onChange={(value) => updateFiling({ seventhProviso: { ...filing.seventhProviso, electricityExpenditureAmount: Math.max(0, Number(value) || 0) } })} type="number" min={100000} required />}
      <label><input type="checkbox" checked={filing.seventhProviso.otherClauseIV} onChange={(event) => updateFiling({ seventhProviso: { ...filing.seventhProviso, otherClauseIV: event.target.checked, clauseIVDetails: event.target.checked ? filing.seventhProviso.clauseIVDetails : [] } })} /> Required to file under other conditions of clause (iv) of the seventh proviso</label>
      {filing.seventhProviso.otherClauseIV && filing.seventhProviso.clauseIVDetails.map((row, index) => <div key={row.id} style={{ ...grid, paddingBottom: 8 }}>
        <Select label={`Condition ${index + 1}`} value={row.nature} onChange={(value) => updateFiling({ seventhProviso: { ...filing.seventhProviso, clauseIVDetails: filing.seventhProviso.clauseIVDetails.map((item) => item.id === row.id ? { ...item, nature: value as '1' | '2' | '3' | '4' } : item) } })} required><option value="1">Condition 1</option><option value="2">Condition 2</option><option value="3">Condition 3</option><option value="4">Condition 4</option></Select>
        <Field label="Amount (₹, if applicable)" value={row.amount} onChange={(value) => updateFiling({ seventhProviso: { ...filing.seventhProviso, clauseIVDetails: filing.seventhProviso.clauseIVDetails.map((item) => item.id === row.id ? { ...item, amount: Math.max(0, Number(value) || 0) } : item) } })} type="number" min={0} />
        <button type="button" onClick={() => updateFiling({ seventhProviso: { ...filing.seventhProviso, clauseIVDetails: filing.seventhProviso.clauseIVDetails.filter((item) => item.id !== row.id) } })}>Remove</button>
      </div>)}
      {filing.seventhProviso.otherClauseIV && <button type="button" onClick={() => updateFiling({ seventhProviso: { ...filing.seventhProviso, clauseIVDetails: [...filing.seventhProviso.clauseIVDetails, { id: `itr3-clauseiv-${Date.now()}`, nature: '1', amount: 0 }] } })}>Add condition</button>}
    </div>}
    </div></Section>
    <Section title="Director and unlisted-equity disclosures" description="These ITR-3 filing-status disclosures are required when the taxpayer was a company director or held unlisted equity during the previous year."><div style={{ display: 'grid', gap: 10 }}><label><input type="checkbox" checked={Boolean(personal.isDirector)} onChange={(event) => updatePersonal({ isDirector: event.target.checked, companyDirectorEntries: event.target.checked ? personal.companyDirectorEntries : [] })} /> Was a director in a company during the year</label>{personal.isDirector && personal.companyDirectorEntries.map((row, index) => <div key={row.id} style={{ ...grid, paddingBottom: 10, borderBottom: '1px solid var(--border)' }}><Field label={`Company ${index + 1} name`} value={row.companyName} onChange={(value) => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.map((item) => item.id === row.id ? { ...item, companyName: value } : item) })} required maxLength={125} /><Select label="Company type" value={row.companyType} onChange={(value) => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.map((item) => item.id === row.id ? { ...item, companyType: value as 'D' | 'F' } : item) })} required><option value="D">Domestic</option><option value="F">Foreign</option></Select><Select label="Shares listed / unlisted" value={row.sharesType} onChange={(value) => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.map((item) => item.id === row.id ? { ...item, sharesType: value as 'L' | 'U' } : item) })} required><option value="L">Listed</option><option value="U">Unlisted</option></Select><Field label="Company PAN" value={row.pan} onChange={(value) => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.map((item) => item.id === row.id ? { ...item, pan: value.toUpperCase().slice(0, 10) } : item) })} pattern={PAN} maxLength={10} /><Field label="DIN" value={row.din} onChange={(value) => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.map((item) => item.id === row.id ? { ...item, din: value.replace(/\D/g, '').slice(0, 8) } : item) })} pattern="[0-9]{8}" maxLength={8} /><button type="button" onClick={() => updatePersonal({ companyDirectorEntries: personal.companyDirectorEntries.filter((item) => item.id !== row.id) })}>Remove</button></div>)}{personal.isDirector && <button type="button" onClick={() => updatePersonal({ companyDirectorEntries: [...personal.companyDirectorEntries, { id: `itr3-director-${Date.now()}`, companyName: '', companyType: 'D', pan: '', sharesType: 'L', din: '' }] })}>Add company directorship</button>}
      <label><input type="checkbox" checked={Boolean(personal.holdsUnlistedShares)} onChange={(event) => updatePersonal({ holdsUnlistedShares: event.target.checked, unlistedEquityEntries: event.target.checked ? personal.unlistedEquityEntries : [] })} /> Held unlisted equity shares during the year</label>
      {personal.holdsUnlistedShares && personal.unlistedEquityEntries.map((row, index) => {
        const updateRow = (patch: Partial<typeof row>): void => updatePersonal({ unlistedEquityEntries: personal.unlistedEquityEntries.map((item) => item.id === row.id ? { ...item, ...patch } : item) });
        return <div key={row.id} style={{ ...grid, paddingBottom: 10, borderBottom: '1px solid var(--border)' }}>
          <Field label={`Company ${index + 1} name`} value={row.companyName} onChange={(value) => updateRow({ companyName: value })} required maxLength={125} />
          <Select label="Company type" value={row.companyType} onChange={(value) => updateRow({ companyType: value as 'D' | 'F' })} required><option value="D">Domestic</option><option value="F">Foreign</option></Select>
          <Field label="Company PAN" value={row.pan} onChange={(value) => updateRow({ pan: value.toUpperCase().slice(0, 10) })} pattern={PAN} maxLength={10} />
          <Field label="Opening shares (number)" value={row.openingShares} onChange={(value) => updateRow({ openingShares: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Opening cost of acquisition (₹)" value={row.openingCost} onChange={(value) => updateRow({ openingCost: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Shares acquired during the year (number)" value={row.acquiredShares} onChange={(value) => updateRow({ acquiredShares: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Date of acquisition" value={row.dateOfAcquisition || ''} onChange={(value) => updateRow({ dateOfAcquisition: value || null })} type="date" />
          <Field label="Face value per share (₹)" value={row.faceValuePerShare} onChange={(value) => updateRow({ faceValuePerShare: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Issue price per share (₹)" value={row.issuePricePerShare} onChange={(value) => updateRow({ issuePricePerShare: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Purchase price per share (₹, if not issue)" value={row.purchasePricePerShare} onChange={(value) => updateRow({ purchasePricePerShare: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Shares transferred during the year (number)" value={row.transferredShares} onChange={(value) => updateRow({ transferredShares: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Sale consideration on transfer (₹)" value={row.transferSaleConsideration} onChange={(value) => updateRow({ transferSaleConsideration: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Closing shares (number)" value={row.closingShares} onChange={(value) => updateRow({ closingShares: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <Field label="Closing cost of acquisition (₹)" value={row.closingCost} onChange={(value) => updateRow({ closingCost: Math.max(0, Number(value) || 0) })} type="number" min={0} />
          <button type="button" onClick={() => updatePersonal({ unlistedEquityEntries: personal.unlistedEquityEntries.filter((item) => item.id !== row.id) })}>Remove</button>
        </div>;
      })}
      {personal.holdsUnlistedShares && <button type="button" onClick={() => updatePersonal({ unlistedEquityEntries: [...personal.unlistedEquityEntries, { id: `itr3-unlisted-${Date.now()}`, companyName: '', companyType: 'D', pan: '', openingShares: 0, openingCost: 0, acquiredShares: 0, dateOfAcquisition: null, faceValuePerShare: 0, issuePricePerShare: 0, purchasePricePerShare: 0, transferredShares: 0, transferSaleConsideration: 0, closingShares: 0, closingCost: 0 }] })}>Add unlisted equity holding</button>}
    </div></Section>
    <Section title="Partner, permanent establishment, and IFSC disclosures — Part A A19(k)-(o)" description="These disclosures apply mainly to partners in firms and non-resident taxpayers with a presence in India."><div style={{ display: 'grid', gap: 10 }}>
      <label><input type="checkbox" checked={filing.isPartnerInFirm} onChange={(event) => updateFiling({ isPartnerInFirm: event.target.checked, partnerInFirmEntries: event.target.checked ? filing.partnerInFirmEntries : [] })} /> Partner in a firm</label>
      {filing.isPartnerInFirm && filing.partnerInFirmEntries.map((row, index) => <div key={row.id} style={{ ...grid, paddingBottom: 8 }}>
        <Field label={`Firm ${index + 1} name`} value={row.firmName} onChange={(value) => updateFiling({ partnerInFirmEntries: filing.partnerInFirmEntries.map((item) => item.id === row.id ? { ...item, firmName: value } : item) })} required maxLength={125} />
        <Field label="Firm PAN" value={row.pan} onChange={(value) => updateFiling({ partnerInFirmEntries: filing.partnerInFirmEntries.map((item) => item.id === row.id ? { ...item, pan: value.toUpperCase().slice(0, 10) } : item) })} required pattern={PAN} maxLength={10} />
        <button type="button" onClick={() => updateFiling({ partnerInFirmEntries: filing.partnerInFirmEntries.filter((item) => item.id !== row.id) })}>Remove</button>
      </div>)}
      {filing.isPartnerInFirm && <button type="button" onClick={() => updateFiling({ partnerInFirmEntries: [...filing.partnerInFirmEntries, { id: `itr3-partner-${Date.now()}`, firmName: '', pan: '' }] })}>Add firm</button>}
      {personal.residentialStatus === 'NR' && <div style={grid}>
        <Select label="Permanent establishment in India" value={filing.nriPEinIndia} onChange={(value) => updateFiling({ nriPEinIndia: value as 'Y' | 'N' | '' })} required><option value="">-- Select --</option><option value="N">No</option><option value="Y">Yes</option></Select>
        <Select label="Significant economic presence in India" value={filing.nriSEPinIndia} onChange={(value) => updateFiling({ nriSEPinIndia: value as 'Y' | 'N' | 'NA' | '' })} required><option value="">-- Select --</option><option value="NA">Not applicable</option><option value="N">No</option><option value="Y">Yes</option></Select>
        {filing.nriSEPinIndia === 'Y' && <><Field label="Aggregate payment transactions (₹)" value={filing.aggrPaymentTransac} onChange={(value) => updateFiling({ aggrPaymentTransac: Math.max(0, Number(value) || 0) })} type="number" min={0} required /><Field label="Number of users" value={filing.numberOfUsers} onChange={(value) => updateFiling({ numberOfUsers: Math.max(0, Number(value) || 0) })} type="number" min={0} required /></>}
      </div>}
      <Select label="IFSC unit with income solely in convertible foreign exchange" value={filing.foreignExchangeFlag} onChange={(value) => updateFiling({ foreignExchangeFlag: value as 'Y' | 'N' | '' })} required><option value="">-- Select --</option><option value="N">No</option><option value="Y">Yes</option></Select>
    </div></Section>
    <Section title="Nature of business or profession — Part A A21" description="Add each main activity using the official five-digit CBDT nature code. The JSON schema requires a code; trade name and description are optional but useful for professional review. Does not apply to businesses declaring income only under sections 44AD, 44ADA, or 44AE — do not list a purely presumptive-scheme business here."><div style={{ display: 'grid', gap: 12 }}>{draft.itr3NatureOfBusiness.map((row, index) => <div key={row.id} style={{ ...grid, padding: 12, border: '1px solid var(--border)', borderRadius: 6, background: 'var(--bg)' }}><Field label={`Activity ${index + 1} official code`} value={row.code} onChange={(value) => onChange({ itr3NatureOfBusiness: draft.itr3NatureOfBusiness.map((item) => item.id === row.id ? { ...item, code: value.replace(/\D/g, '').slice(0, 5) } : item) })} required pattern="[0-9]{5}" maxLength={5} help="Use the exact five-digit code from the CBDT nature-of-business list." /><Field label="Trade name" value={row.tradeName} onChange={(value) => onChange({ itr3NatureOfBusiness: draft.itr3NatureOfBusiness.map((item) => item.id === row.id ? { ...item, tradeName: value } : item) })} maxLength={125} /><Field label="Activity description" value={row.description} onChange={(value) => onChange({ itr3NatureOfBusiness: draft.itr3NatureOfBusiness.map((item) => item.id === row.id ? { ...item, description: value } : item) })} maxLength={125} /><button type="button" onClick={() => onChange({ itr3NatureOfBusiness: draft.itr3NatureOfBusiness.filter((item) => item.id !== row.id) })}>Remove activity</button></div>)}</div><div style={{ display: 'flex', gap: 10, alignItems: 'center', marginTop: 12 }}><button type="button" disabled={draft.itr3NatureOfBusiness.length >= 3} onClick={() => onChange({ itr3NatureOfBusiness: [...draft.itr3NatureOfBusiness, { id: `itr3-nature-${Date.now()}`, code: '', tradeName: '', description: '' }] })}>Add activity</button><span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{draft.itr3NatureOfBusiness.length}/3 activities entered</span></div></Section>
    <Section title="Audit information — Part A A20" description="Answer the official ITR-3 audit questionnaire. These fields are persisted in PartA_GEN2.AuditInfo and determine whether audit evidence and Part A-OI/QD schedules are required."><div style={grid}>
      <Select label="Liable under section 44AA" value={draft.itr3AuditInfo.liableSec44AA} onChange={(value) => onChange({ itr3AuditInfo: { liableSec44AA: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
      <Select label="Income declared only under presumptive sections" value={draft.itr3AuditInfo.incomeDeclaredUnderPresumptive} onChange={(value) => onChange({ itr3AuditInfo: { incomeDeclaredUnderPresumptive: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
      <Select label="Liable under section 44AB" value={draft.itr3AuditInfo.liableSec44AB} onChange={(value) => onChange({ itr3AuditInfo: { liableSec44AB: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
      <Select label="Liable under section 92E" value={draft.itr3AuditInfo.liableSec92E} onChange={(value) => onChange({ itr3AuditInfo: { liableSec92E: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
      {draft.itr3AuditInfo.liableSec92E === 'Y' && <Select label="Have the accounts been audited under section 92E?" value={draft.itr3AuditInfo.auditedUnder92E} onChange={(value) => onChange({ itr3AuditInfo: { auditedUnder92E: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>}
      {draft.itr3AuditInfo.liableSec44AB === 'Y' && <Select label="Accounts audited under the Income-tax Act" value={draft.itr3AuditInfo.accountAudit} onChange={(value) => onChange({ itr3AuditInfo: { accountAudit: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>}
      {(draft.itr3AuditInfo.liableSec44AB === 'Y' || draft.itr3AuditInfo.incomeDeclaredUnderPresumptive === 'Y') && <Select label="Sales / turnover / gross receipts" value={draft.itr3AuditInfo.totalSalesBand} onChange={(value) => onChange({ itr3AuditInfo: { totalSalesBand: value as 'Upto1CR' | 'Upto10CR' | 'MoreThan10CR' | '' } } as DraftPatch)} required><option value="">-- Select band --</option><option value="Upto1CR">Up to ₹1 crore</option><option value="Upto10CR">More than ₹1 crore up to ₹10 crore</option><option value="MoreThan10CR">More than ₹10 crore</option></Select>}
      {draft.itr3AuditInfo.totalSalesBand === 'Upto10CR' && <><Select label="Cash receipts as percentage" value={draft.itr3AuditInfo.receiptsCashBand} onChange={(value) => onChange({ itr3AuditInfo: { receiptsCashBand: value as 'Upto5Per' | 'MoreThan5Per' | '' } } as DraftPatch)} required><option value="">-- Select --</option><option value="Upto5Per">Up to 5%</option><option value="MoreThan5Per">More than 5%</option></Select><Select label="Cash payments as percentage" value={draft.itr3AuditInfo.paymentsCashBand} onChange={(value) => onChange({ itr3AuditInfo: { paymentsCashBand: value as 'Upto5Per' | 'MoreThan5Per' | '' } } as DraftPatch)} required><option value="">-- Select --</option><option value="Upto5Per">Up to 5%</option><option value="MoreThan5Per">More than 5%</option></Select></>}
      {draft.itr3AuditInfo.liableSec44AB === 'Y' && <Select label="Section 44AB condition" value={draft.itr3AuditInfo.condition44AB} onChange={(value) => onChange({ itr3AuditInfo: { condition44AB: value as 'bi' | 'bii' | 'biii' | '' } } as DraftPatch)} required><option value="">-- Select condition --</option><option value="bi">Condition (i): turnover exceeds specified limit</option><option value="bii">Condition (ii): presumptive scheme not opted</option><option value="biii">Condition (iii): other applicable condition</option></Select>}
      </div>{draft.itr3AuditInfo.condition44AB === 'bii' && <div style={{ ...grid, marginTop: 14 }}>
        <Select label="Declared lower than deemed profit under 44AD" value={draft.itr3AuditInfo.presumptive44AD} onChange={(value) => onChange({ itr3AuditInfo: { presumptive44AD: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
        <Select label="Declared lower than deemed profit under 44ADA" value={draft.itr3AuditInfo.presumptive44ADA} onChange={(value) => onChange({ itr3AuditInfo: { presumptive44ADA: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
        <Select label="Declared lower than deemed profit under 44AE" value={draft.itr3AuditInfo.presumptive44AE} onChange={(value) => onChange({ itr3AuditInfo: { presumptive44AE: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
        <Select label="Declared lower than deemed profit under 44BB" value={draft.itr3AuditInfo.presumptive44BB} onChange={(value) => onChange({ itr3AuditInfo: { presumptive44BB: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
      </div>}<div style={grid}>
      {draft.itr3AuditInfo.liableSec44AB === 'Y' && <Select label="Audit accountant appointed" value={draft.itr3AuditInfo.auditAccountant} onChange={(value) => onChange({ itr3AuditInfo: { auditAccountant: value as 'Y' | 'N' } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>}
    </div>{draft.itr3AuditInfo.liableSec44AB === 'Y' && <div style={{ ...grid, marginTop: 14 }}><Field label="Audit report furnished date" value={draft.itr3AuditInfo.auditReportFurnishDate || ''} onChange={(value) => onChange({ itr3AuditInfo: { auditReportFurnishDate: value || null } } as DraftPatch)} type="date" required /><Field label="Form 3CB/3CD acknowledgement number" value={draft.itr3AuditInfo.acknowledgement44AB} onChange={(value) => onChange({ itr3AuditInfo: { acknowledgement44AB: value.replace(/\D/g, '').slice(0, 15) } } as DraftPatch)} required maxLength={15} /><Field label="Auditor / firm name" value={draft.itr3AuditInfo.auditorName} onChange={(value) => onChange({ itr3AuditInfo: { auditorName: value } } as DraftPatch)} required maxLength={125} /><Field label="Auditor / firm PAN" value={draft.itr3AuditInfo.auditorPAN} onChange={(value) => onChange({ itr3AuditInfo: { auditorPAN: value.toUpperCase().slice(0, 10) } } as DraftPatch)} required pattern={PAN} maxLength={10} /><Field label="Auditor Aadhaar" value={draft.itr3AuditInfo.auditorAadhaar} onChange={(value) => onChange({ itr3AuditInfo: { auditorAadhaar: value.replace(/\D/g, '').slice(0, 12) } } as DraftPatch)} pattern="[0-9]{12}" maxLength={12} /></div>}{draft.itr3AuditInfo.auditedUnder92E === 'Y' && <div style={{ ...grid, marginTop: 14 }}><Field label="Section 92E audit date" value={draft.itr3AuditInfo.auditReport92EDate || ''} onChange={(value) => onChange({ itr3AuditInfo: { auditReport92EDate: value || null } } as DraftPatch)} type="date" required /><Field label="Section 92E acknowledgement number" value={draft.itr3AuditInfo.acknowledgement92E} onChange={(value) => onChange({ itr3AuditInfo: { acknowledgement92E: value.replace(/\D/g, '').slice(0, 15) } } as DraftPatch)} required maxLength={15} /></div>}</Section>
    <Section title="Other audit reports — Part A A20(diii)" description="Required when the return claims a deduction under a section that has its own mandatory audit report (e.g. 10AA, 80-IA, 80-IB, 115JC)."><div style={{ display: 'grid', gap: 10 }}>
      {draft.itr3AuditInfo.otherAuditReportEntries.map((row, index) => <div key={row.id} style={{ ...grid, paddingBottom: 8 }}>
        <Select label={`Report ${index + 1} section`} value={row.auditedSection} onChange={(value) => onChange({ itr3AuditInfo: { otherAuditReportEntries: draft.itr3AuditInfo.otherAuditReportEntries.map((item) => item.id === row.id ? { ...item, auditedSection: value as typeof row.auditedSection } : item) } } as DraftPatch)} required><option value="">-- Select section --</option>{['10A', '10AA', '44DA', '50B', '80-IA', '80-IAB', '80-IAC', '80-IB', '80-IC', '80-ID', '80-IE', '80JJAA', '80LA', '115JC'].map((code) => <option key={code} value={code}>{code}</option>)}</Select>
        <Select label="Audited" value={row.auditFlag} onChange={(value) => onChange({ itr3AuditInfo: { otherAuditReportEntries: draft.itr3AuditInfo.otherAuditReportEntries.map((item) => item.id === row.id ? { ...item, auditFlag: value as 'Y' | 'N' } : item) } } as DraftPatch)} required><option value="N">No</option><option value="Y">Yes</option></Select>
        <Field label="Date of audit" value={row.dateOfAudit || ''} onChange={(value) => onChange({ itr3AuditInfo: { otherAuditReportEntries: draft.itr3AuditInfo.otherAuditReportEntries.map((item) => item.id === row.id ? { ...item, dateOfAudit: value || null } : item) } } as DraftPatch)} type="date" />
        <Field label="Acknowledgement number" value={row.ackNumOth} onChange={(value) => onChange({ itr3AuditInfo: { otherAuditReportEntries: draft.itr3AuditInfo.otherAuditReportEntries.map((item) => item.id === row.id ? { ...item, ackNumOth: value.replace(/\D/g, '').slice(0, 15) } : item) } } as DraftPatch)} pattern="[0-9]{15}" maxLength={15} />
        <button type="button" onClick={() => onChange({ itr3AuditInfo: { otherAuditReportEntries: draft.itr3AuditInfo.otherAuditReportEntries.filter((item) => item.id !== row.id) } } as DraftPatch)}>Remove</button>
      </div>)}
      <button type="button" onClick={() => onChange({ itr3AuditInfo: { otherAuditReportEntries: [...draft.itr3AuditInfo.otherAuditReportEntries, { id: `itr3-otheraudit-${Date.now()}`, auditedSection: '', auditFlag: 'N', dateOfAudit: null, ackNumOth: '' }] } } as DraftPatch)}>Add other audit report</button>
    </div></Section>
    <Section title="Audit under another Act — Part A A20(e)" description="If accounts have also been audited under any Act other than the Income-tax Act, furnish details of each audit."><div style={{ display: 'grid', gap: 10 }}>
      {draft.itr3AuditInfo.auditUnderOtherActEntries.map((row, index) => <div key={row.id} style={{ ...grid, paddingBottom: 8 }}>
        <Select label={`Act ${index + 1}`} value={row.act} onChange={(value) => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: draft.itr3AuditInfo.auditUnderOtherActEntries.map((item) => item.id === row.id ? { ...item, act: value as typeof row.act } : item) } } as DraftPatch)} required><option value="">-- Select Act --</option><option value="1">Banking Regulation Act, 1949</option><option value="2">Central Excise Act, 1944</option><option value="3">Central Sales Tax Act, 1956</option><option value="4">Central Goods and Services Tax Act, 2017</option><option value="5">Charitable And Religious Trusts Act, 1920</option><option value="6">Companies Act, 2013</option><option value="7">Electricity Act, 2003</option><option value="8">Employees Provident Fund and Misc. Provisions Act, 1952</option><option value="9">Foreign Exchange Management Act, 1999</option><option value="10">Government Superannuation Fund Act, 1956</option><option value="11">Indian Trusts Act, 1882</option><option value="12">Integrated Goods and Services Tax Act, 2017</option><option value="13">Limited Liability Partnership Act, 2008</option><option value="14">Payment of Gratuity Act, 1972</option><option value="15">SEBI Act, 1992</option><option value="16">Securities Contract (Regulation) Act, 1956</option><option value="17">State Goods and Services Tax Act, 2017</option><option value="18">Union Territories Goods and Services Tax Act, 2017</option><option value="19">Others</option></Select>
        {row.act === '19' && <Field label="Specify Act" value={row.actOthers} onChange={(value) => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: draft.itr3AuditInfo.auditUnderOtherActEntries.map((item) => item.id === row.id ? { ...item, actOthers: value } : item) } } as DraftPatch)} required maxLength={125} />}
        <Field label="Section audited under" value={row.auditedSection} onChange={(value) => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: draft.itr3AuditInfo.auditUnderOtherActEntries.map((item) => item.id === row.id ? { ...item, auditedSection: value } : item) } } as DraftPatch)} required maxLength={30} />
        <Field label="Date of audit" value={row.dateOfAudit || ''} onChange={(value) => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: draft.itr3AuditInfo.auditUnderOtherActEntries.map((item) => item.id === row.id ? { ...item, dateOfAudit: value || null } : item) } } as DraftPatch)} type="date" required />
        <button type="button" onClick={() => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: draft.itr3AuditInfo.auditUnderOtherActEntries.filter((item) => item.id !== row.id) } } as DraftPatch)}>Remove</button>
      </div>)}
      <button type="button" onClick={() => onChange({ itr3AuditInfo: { auditUnderOtherActEntries: [...draft.itr3AuditInfo.auditUnderOtherActEntries, { id: `itr3-otheract-${Date.now()}`, act: '', actOthers: '', auditedSection: '', dateOfAudit: null }] } } as DraftPatch)}>Add audit under another Act</button>
    </div></Section>
    <Section title="Verification" description="The final declaration is required before CBDT JSON generation."><div style={grid}>
      <Select label="Verification capacity" value={verification.capacity} onChange={(value) => updateVerification({ capacity: value as ReturnDraft['verification']['capacity'] })} required><option value="SELF">Self</option><option value="REPRESENTATIVE">Representative assessee</option><option value="KARTA">Karta</option><option value="PARTNER">Authorised partner</option></Select>
      <Field label="Place" value={verification.place} onChange={(value) => updateVerification({ place: value })} required maxLength={50} />
      <Field label="Verification date" value={verification.date || ''} onChange={(value) => updateVerification({ date: value || null })} type="date" required />
    </div>
    {verification.capacity === 'REPRESENTATIVE' && <div style={{ marginTop: 14 }}><h4 style={{ margin: '0 0 8px', fontSize: 13 }}>Representative assessee (Part A A19(i))</h4><div style={grid}>
      <Field label="Name of representative assessee" value={filing.representative?.name || ''} onChange={(value) => updateFiling({ representative: { name: value, email: filing.representative?.email || '', mobileCountryCode: filing.representative?.mobileCountryCode || '91', mobile: filing.representative?.mobile || '', pan: filing.representative?.pan } })} required maxLength={125} />
      <Field label="Email-ID of representative assessee" value={filing.representative?.email || ''} onChange={(value) => updateFiling({ representative: { name: filing.representative?.name || '', email: value.trim(), mobileCountryCode: filing.representative?.mobileCountryCode || '91', mobile: filing.representative?.mobile || '', pan: filing.representative?.pan } })} type="email" required maxLength={125} />
      <Field label="Contact number of representative assessee" value={filing.representative?.mobile || ''} onChange={(value) => updateFiling({ representative: { name: filing.representative?.name || '', email: filing.representative?.email || '', mobileCountryCode: filing.representative?.mobileCountryCode || '91', mobile: value.replace(/\D/g, '').slice(0, 10), pan: filing.representative?.pan } })} required pattern="[1-9][0-9]{4,9}" maxLength={10} />
    </div></div>}
    <label style={{ display: 'flex', gap: 8, alignItems: 'flex-start', marginTop: 14, fontSize: 13 }}><input type="checkbox" checked={verification.declarationAccepted} onChange={(event) => updateVerification({ declarationAccepted: event.target.checked })} />I, {personal.name || '[name]'}, son/daughter of {personal.fatherName || '[father\'s name]'}, declare that the information given in this return and its schedules is correct and complete.</label></Section>
    <Section title="Bank accounts and refund" description="Add reportable bank accounts in the canonical draft. Select the refund account in the account manager."><BankAccountManager data={{ accounts: draft.bankAccounts }} onChange={onBanksChange} /></Section>
  </div>;
}

export default ITR3PersonalInfoPage;
