import React from 'react';
import type { TaxChallan, TcsCredit, TdsCredit } from '../domain/returns/types';

export interface ITR3TaxPaymentEditorProps { assessmentYear: string; tds: TdsCredit[]; tcs: TcsCredit[]; challans: TaxChallan[]; onTdsChange: (rows: TdsCredit[]) => void; onTcsChange: (rows: TcsCredit[]) => void; onChallansChange: (rows: TaxChallan[]) => void; }
const uid = (prefix: string): string => globalThis.crypto?.randomUUID?.() ?? `${prefix}-${Date.now()}`;
const num = (value: string): number => Math.max(0, Number(value) || 0);
const years = ['2025','2024','2023','2022','2021','2020','2019','2018','2017','2016','2015','2014','2013','2012','2011','2010','2009','2008'];
/** Dedicated editor for official ITR-3 tax-payment schedules. */
export default function ITR3TaxPaymentEditor({ assessmentYear, tds, tcs, challans, onTdsChange, onTcsChange, onChallansChange }: ITR3TaxPaymentEditorProps): React.ReactElement {
  const changeTds = (id: string, patch: Partial<TdsCredit>): void => onTdsChange(tds.map((row) => row.id === id ? { ...row, ...patch } : row));
  const changeTcs = (id: string, patch: Partial<TcsCredit>): void => onTcsChange(tcs.map((row) => row.id === id ? { ...row, ...patch } : row));
  const changeChallan = (id: string, patch: Partial<TaxChallan>): void => onChallansChange(challans.map((row) => row.id === id ? { ...row, ...patch } : row));
  const addChallan = (): void => onChallansChange([...challans, { id: uid('it'), kind: 'ADVANCE_TAX', bsrCode: '', depositDate: '', challanSerialNo: 0, amount: 0, cin: '' }]);
  const addTds = (schedule: TdsCredit['schedule']): void => onTdsChange([...tds, { id: uid(schedule), section: schedule === 'TDS1' ? '192' : '194A', deductorName: '', deductorTAN: '', deductorPAN: '', certificateNo: '', grossAmount: 0, taxDeducted: 0, deductionDate: '', uniqueTransactionNo: '', financialYear: '2025-26', verified26AS: false, claimedInReturn: true, schedule, tdsSectionCode: '', deductedYr: '', headOfIncome: 'OS', tdsCreditName: 'S', panOfOtherPerson: '', aadhaarOfOtherPerson: '', broughtFwdTDSAmt: 0, amtCarriedFwd: 0, claimOutOfTotTDSOnAmtPaid: 0, taxDeductCreditDtls: { taxDeductedOwnHands: 0, taxDeductedIncome: 0, taxDeductedTDS: 0, taxClaimedOwnHands: 0, taxClaimedIncome: 0, taxClaimedTDS: 0, taxClaimedSpouseOthPrsnPAN: '', spouseOthPrsnAadhaar: '' }, nameOfTenant: '', grsRcptToTaxDeduct: 0, tdsClaimed: 0, panOfTenant: '', aadhaarOfTenant: '', tcsCreditOwner: '1', panOfSpouseOrOthrPrsn: '', tcsAmtCollOwnHand: 0, tcsAmtCollSpouseOrOthrHand: 0, tcsClaimedAmtCollOwnHand: 0, tcsClaimedAmtCollSpouseOrOthrHand: 0 }]);
  const addTcs = (): void => onTcsChange([...tcs, { id: uid('tcs'), collectorName: '', collectorTAN: '', grossAmount: 0, taxCollected: 0, claimedInReturn: true, tcsCreditOwner: '1', panOfSpouseOrOthrPrsn: '', deductedYr: '', broughtFwdTDSAmt: 0, tcsAmtCollOwnHand: 0, tcsAmtCollSpouseOrOthrHand: 0, tcsClaimedAmtCollOwnHand: 0, tcsClaimedAmtCollSpouseOrOthrHand: 0, claimedPANOfSpouseOrOthrPrsn: '' }]);
  const field = (label: string, value: string | number, onChange: (value: string) => void, type = 'text'): React.ReactElement => <label>{label}<input type={type} value={value} min={type === 'number' ? 0 : undefined} onChange={(event) => onChange(event.target.value)} /></label>;
  return <div style={shell}><h2>ITR-3 tax payments and credits</h2><p>Assessment year {assessmentYear}. Totals and credit eligibility remain backend-computed and read-only.</p>
    <section style={section}><h3>Schedule IT — TaxPayment</h3><button type="button" onClick={addChallan}>＋ Add challan</button>{challans.map((row) => <div style={grid} key={row.id}>{field('BSRCode', row.bsrCode, (v) => changeChallan(row.id, { bsrCode: v.toUpperCase() }))}{field('DateDep', row.depositDate, (v) => changeChallan(row.id, { depositDate: v }), 'date')}{field('SrlNoOfChaln', row.challanSerialNo, (v) => changeChallan(row.id, { challanSerialNo: Math.min(99999, Math.trunc(num(v))) }), 'number')}{field('Amt', row.amount, (v) => changeChallan(row.id, { amount: num(v) }), 'number')}{field('CIN', row.cin, (v) => changeChallan(row.id, { cin: v }))}<button type="button" onClick={() => onChallansChange(challans.filter((item) => item.id !== row.id))}>Remove</button></div>)}</section>
    {(['TDS1','TDS2','TDS3'] as const).map((schedule) => <section style={section} key={schedule}><h3>Schedule {schedule}</h3><button type="button" onClick={() => addTds(schedule)}>＋ Add row</button>{tds.filter((row) => row.schedule === schedule).map((row) => <div style={grid} key={row.id}>{field(schedule === 'TDS3' ? 'PANOfBuyerTenant' : 'EmployerOrDeductorName', schedule === 'TDS3' ? row.panOfTenant : row.deductorName, (v) => changeTds(row.id, schedule === 'TDS3' ? { panOfTenant: v } : { deductorName: v }))}{field(schedule === 'TDS3' ? 'Buyer/tenant name' : 'TANOfDeductor', schedule === 'TDS3' ? row.nameOfTenant : row.deductorTAN, (v) => changeTds(row.id, schedule === 'TDS3' ? { nameOfTenant: v } : { deductorTAN: v.toUpperCase() }))}{field('TDSSection', row.section, (v) => changeTds(row.id, { section: v, tdsSectionCode: v }))}{field('GrossAmount', row.grossAmount, (v) => changeTds(row.id, { grossAmount: num(v) }), 'number')}{field('TDSDeducted', row.taxDeducted, (v) => changeTds(row.id, { taxDeducted: num(v) }), 'number')}{field('BroughtFwdTDSAmt', row.broughtFwdTDSAmt, (v) => changeTds(row.id, { broughtFwdTDSAmt: num(v) }), 'number')}{field('AmtCarriedFwd', row.amtCarriedFwd, (v) => changeTds(row.id, { amtCarriedFwd: num(v) }), 'number')}<button type="button" onClick={() => onTdsChange(tds.filter((item) => item.id !== row.id))}>Remove</button></div>)}</section>)}
    <section style={section}><h3>Schedule TCS</h3><button type="button" onClick={addTcs}>＋ Add row</button>{tcs.map((row) => <div style={grid} key={row.id}>{field('CollectorName', row.collectorName, (v) => changeTcs(row.id, { collectorName: v }))}{field('CollectorTAN', row.collectorTAN, (v) => changeTcs(row.id, { collectorTAN: v.toUpperCase() }))}{field('GrossAmount', row.grossAmount, (v) => changeTcs(row.id, { grossAmount: num(v) }), 'number')}{field('TotalTCSAmt', row.taxCollected, (v) => changeTcs(row.id, { taxCollected: num(v) }), 'number')}{field('BroughtFwdTDSAmt', row.broughtFwdTDSAmt, (v) => changeTcs(row.id, { broughtFwdTDSAmt: num(v) }), 'number')}<button type="button" onClick={() => onTcsChange(tcs.filter((item) => item.id !== row.id))}>Remove</button></div>)}</section><p>Deducted year options: {years.join(', ')}. Backend computes TotalTaxPayments, TotalTDSonSalaries, TotalTDSonOthThanSals, TotalTDS3OnOthThanSal, and TotalSchTCS.</p></div>;
}
const shell: React.CSSProperties = { display: 'grid', gap: 16 };
const section: React.CSSProperties = { border: '1px solid #eaecf0', borderRadius: 8, padding: 16, display: 'grid', gap: 12 };
const grid: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 10, alignItems: 'end' };
