# Reference-only transcription of the official CBDT ITR-4 Validation Rules AY 2026-27,
# (from Reference Docs by CBDT & ITD/Official Validations/CBDT_e-Filing_ITR 4_Validation Rules_AY 2026-27 (1).pdf)
# kept here so the cross-reference audit doesn't need to re-read the source PDF from scratch.
# Not imported by application code — used only as input to ad-hoc audit/diff scripts.
# CATEGORY_A/B/D mirror the PDF's own defect-category table (A = blocks upload, B = upload
# allowed with defect flagged, D = deduction/claim not entertained without supporting form).
# Numbering follows the PDF exactly, including its own gap (no rule 400/401 in Category A).

CATEGORY_A = {
1: "44AD/44ADA/44AE income disclosed in Part B GTI but Schedule BP not filled",
2: "Business income in Part B GTI inconsistent with Schedule BP amount",
3: "Sch BP E17 Total capital+liabilities = Partners capital+Secured+Unsecured loans+Advances+Sundry creditors+Other liabilities",
4: "Sch BP E25 Total assets = Fixed assets+Investments+Inventories+Sundry debtors+Balance with banks+Cash-in-hand+Loans and advances+Other assets",
5: "44AD presumptive income >= 6% of digital-mode turnover/receipts",
6: "44AD presumptive income >= 8% of other-mode turnover/receipts",
7: "44AD total presumptive income = 6% digital + 8% other",
8: "Income u/s 44AD > gross receipts or turnover",
9: "ITR-4 filed but gross receipt/income u/s 44AD > Rs 3 crore",
10: "44AD not applicable for commission agents and s.44AA(1) professionals",
11: "Sch BP: 44AD income declared => business code u/s 44AD mandatory",
12: "Sch BP: 44AD business code selected => income u/s 44AD mandatory",
13: "Income u/s 44ADA > corresponding gross receipts",
14: "Presumptive income u/s 44ADA < 50% of gross turnover/receipts",
15: "44ADA not applicable for persons carrying on business",
16: "Sch BP: 44ADA income declared => business code u/s 44ADA mandatory",
17: "Sch BP: 44ADA business code selected => income u/s 44ADA mandatory",
18: "Total Chapter VI-A deductions inconsistent with breakup of individual deductions",
19: "Chapter VI-A deductions > Gross Total Income",
20: "Assessee is Firm and claiming 80C/80CCC/80CCD(1)",
21: "Old regime: sum of 80C+80CCC+80CCD(1) should not exceed Rs 1,50,000",
22: "Old regime, employer category CG/SG/PSU/Others-Pensioners or NA: 80CCD(1) should not exceed 20% of GTI",
23: "Assessee not being individual claimed 80CCD(1) (not allowable)",
24: "Taxpayer other than individual claiming 80CCD(1B)",
25: "Old regime: 80CCD(2) should not exceed 10% of salary if employer other than Central/State Govt",
26: "80CCD(2) claimed by HUF or Firm (other than LLP)",
27: "Firm (other than LLP) claiming 80D",
28: "Firm has claimed 80DD",
29: "Old regime, 80DD claimed: eligible category description required",
30: "Old regime, 80DDB claimed: eligible category description required",
31: "Assessee being Firm and claiming 80DDB",
32: "80EE claimed by HUF or Firm (other than LLP)",
33: "80EEB claimed by HUF or Firm (other than LLP)",  # (source table's own row 33 mirrors 80EE text; verbatim as printed)
34: "Old regime, 80G claimed but Schedule 80G details not provided",
35: "Old regime: Sch 80G computed deduction > eligible amount",
36: "Old regime: Sch VIA 80G claimed > eligible donation per Sch 80G",
37: "Old regime: 80GG max = lower of Rs 60,000 or 25% of total income excl LTCG",
38: "Old regime: 80TTA restricted to savings-account interest from other sources",
39: "Old regime: 80TTA cannot be claimed by senior citizen (DOB on/before 01.04.1966)",
40: "Old regime: non-senior-citizen (DOB on/after 02.04.1966) cannot claim 80TTB",
41: "Old regime, senior citizen: 80TTB restricted to interest (savings+deposits) from OS or Rs 50,000, lower",
42: "Old regime: 80U fixed Rs 75,000 for 'Self with disability'",
43: "HUF/Firm claiming 80U",
44: "Old regime, 80U claimed: eligible category description not provided",
45: "Part A General: name/email/contact of representative mandatory if verification capacity = Representative",
46: "Total income = GTI - Total deductions (GTI includes LTCG u/s 112A)",
47: "Old regime: 80CCD(2) should not exceed 14% of salary if employer CG/SG",
48: "Name entered does not match PAN database",
49: "Old regime: GTI must equal total of Business&Profession+Salary+HP+OS+LTCG112A",
50: "HUF or Firm claiming 87A rebate",
51: "87A rebate claimed by resident individual with total income (incl LTCG112A) > Rs 5,00,000 under old regime",
52: "Tax after rebate = Tax payable on total income - Rebate 87A",
53: "Total Tax and cess = Tax payable after rebate + Health & Education Cess",
54: "Total Tax Fee Interest = Balance Tax after Relief + Interest 234A/234B/234C + Fees 234-I + Fee 234F",
55: "Sch Part B GTI, Sl B3iii: Annual Value = output of B3i-B3ii",
56: "Sch Income Details: Balance Tax after relief = Total Tax&Cess - Relief u/s 89(1)",
57: "HP standard deduction = 30% of Annual Value",
58: "Gross rent received/receivable/lettable value is zero/null and assessee claims municipal tax",
59: "Let-out/deemed let-out: gross rent received/lettable value is zero/null",
60: "Sch GTI Sl B3k: HP income chargeable (f-i-j) != sum of individual HP values",
61: "Sch Income Details: tax paid to local authorities not allowed for self-occupied property",
62: "Sch Income Details: OS income = sum of individual OS columns",
63: "Gross salary = salary 17(1) + perquisites 17(2) + profits in lieu 17(3)",
64: "Sch GTI: Net Salary = Gross salary - allowances exempt u/s 10",
65: "Sch Income Details B2(iv) deductions u/s 16 = B2[iva+ivb+ivc]",
66: "Sch Income Details B2v income chargeable under Salaries = B2iii-B2iv",
67: "Old regime, CG/SG/PSU employees: entertainment allowance 16(ii) <= lower of Rs 5,000 or 1/5th basic salary",
68: "Old regime: no entertainment allowance 16(ii) for non-CG/SG/PSU employees",
69: "Total allowances exempt u/s 10 <= sum of B2(i)(a)+B2(i)(b)+B2(i)(c)",
70: "Old regime: 10(5) LTC/LTA received cannot exceed Salary 17(1)",
71: "10(6) embassy official exemption cannot exceed Gross Salary",
72: "10(7) foreign-service allowance exemption cannot exceed Gross Salary",
73: "10(10) death-cum-retirement gratuity cannot exceed Rs 20,00,000 if employer PSU/PSU-Pensioners/Others-Pensioners/Others",
74: "10(10A) commuted pension cannot exceed Salary 17(1)",
75: "10(10AA) earned leave encashment cannot exceed Salary 17(1)",
76: "10(10C) VRS/termination amount cannot exceed Rs 5,00,000",
77: "Only one of 10(10B)(i)/10(10B)(ii)/10(10C) can be selected",
78: "10(10CC) employer-paid perquisite tax cannot exceed Value of perquisites 17(2)",
79: "Old regime: 10(13A) HRA cannot exceed 1/3rd (33.33%)/50% of Salary 17(1)",
80: "Old regime: 10(14)(i) prescribed allowances cannot exceed Salary 17(1)",
81: "Old regime: 10(14)(ii) personal-expense allowances cannot exceed Salary 17(1)",
82: "Sec 10(10BC) disaster compensation dropdown cannot be selected >1 time",
83: "Sec 10(10D) life insurance sum dropdown cannot be selected >1 time",
84: "Sec 10(11) statutory PF dropdown cannot be selected >1 time",
85: "Sec 10(12) recognised PF dropdown cannot be selected >1 time",
86: "Sec 10(13) approved superannuation dropdown cannot be selected >1 time",
87: "Sec 10(16) scholarship dropdown cannot be selected >1 time",
88: "Old regime: Sec 10(17) MP/MLA/MLC allowance dropdown cannot be selected >1 time",
89: "Sec 10(17A) Government award dropdown cannot be selected >1 time",
90: "Sec 10(18) gallantry-award pension dropdown cannot be selected >1 time",
91: "Defence medical disability pension dropdown cannot be selected >1 time",
92: "Sec 10(19) armed-forces family pension dropdown cannot be selected >1 time",
93: "Sec 10(26) NE/Ladakh income dropdown cannot be selected >1 time",
94: "Sec 10(26AAA) Sikkimese income dropdown cannot be selected >1 time",
95: "57(iia) deduction allowed only if Family pension selected from OS dropdown",
96: "Old regime: 57(iia) cannot exceed 1/3rd of Family pension or Rs 15,000, lower",
97: "44AE presumptive income = Presumptive Income from Goods Carriage minus Salary and interest paid to partners (Firm other than LLP)",
98: "Sch 80G donee PAN same as Assessee PAN or PAN at Verification",
99: "Sch 80G table A: cash or other-mode donation mandatory",
100: "Sch 80G table B: cash or other-mode donation mandatory",
101: "Sch 80G table C: cash or other-mode donation mandatory",
102: "Sch 80G table D: cash or other-mode donation mandatory",
103: "Sch 80G table E = sum of A+B+C+D",
104: "Sch 80G table A total donation = cash + other mode",
105: "Sch 80G table B total donation = cash + other mode",
106: "Sch 80G table C total donation = cash + other mode",
107: "Sch 80G table D total donation = cash + other mode",
108: "Old regime: Sch 80G same-PAN cash donations aggregate > Rs 2,000 => eligible amount restricted to 0",
109: "Sch 80G: same donee PAN cannot repeat (except a specific ARN-linked PAN); table D exempt if ARN unique/blank",
110: "Sch IT total col-4 tax paid = sum of individual values",
111: "Sch TCS: amount claimed this year > tax collected",
112: "Sch TCS total col-5 TCS credit claimed this year = sum of individual values",
113: "Sch TDS2(i)/(ii) (other than salary): amount claimed this year > tax deducted",
114: "Sch TDS(2): year of tax deduction cannot be 0/null if brought-forward claim",
115: "Sch TDS2(i)/(ii): unclaimed brought-forward TDS and current-FY TDS details must be in different rows",
116: "Sch TDS-2(ii): claim of TDS in Sl.6 cannot exceed income disclosed in Sl.7",
117: "Sch TDS-2(i): claim of TDS in Sl.6 cannot exceed income disclosed in Sl.7",
118: "Sch TDS1 total col-4 total tax deducted = sum of individual values",
119: "Sch TDS2 total col-6 TDS credit claimed this year = sum of individual values",
120: "Sch TDS3 total col-6 TDS credit claimed this year = sum of individual values",
121: "Sch TDS2(i): TDS claimed in col 6 => corresponding gross amount (col7)/head of income (col8) mandatory",
122: "Sch TDS2(ii): TDS claimed in col 6 => corresponding gross amount (col7)/head of income (col8) mandatory",
123: "IFSC under Bank Details/Sch 80G/Sch 80GGC must match RBI/GIFT IFSC database",
124: "Tax computation disclosed but GTI is zero",
125: "Income details/tax computation not disclosed but Taxes Paid details disclosed",
126: "TDS/TCS/tax paid claimed in Taxes Paid & Verification inconsistent with Sch IT/TDS1/TDS2/TCS",
127: "Sum of TDS+TCS+Advance Tax+Self-Assessment Tax != Total Taxes Paid",
128: "Refund claimed inconsistent with Total Taxes Paid - Total Tax Fee & Interest",
129: "Tax payable inconsistent with Total Tax Fee&Interest - Total Taxes Paid",
130: "Agriculture income shown as exempt > Rs 5,000 or selected more than once",
131: "Sch Taxes Paid & Verification: Total TDS Claimed = sum of TDS1+TDS2(i)+TDS2(ii)",
132: "Sch Taxes Paid & Verification: Total TCS Claimed = sum of TCS schedule",
133: "Sch Taxes Paid & Verification: Total Advance Tax = sum of Sch IT entries dated in PY",
134: "Sch Taxes Paid & Verification: Total Self-Assessment Tax = sum of Sch IT entries dated after 31 Mar of PY",
135: "Field E5 > 0 but Schedule 44AE not filed",
136: "Presumptive income from Goods Carriage u/s 44AE != amount in 'Presumptive income u/s 44AE'",
137: "Sch BP: 44AE income declared => business code u/s 44AE mandatory",
138: "Sch BP: 44AE business code selected => income u/s 44AE mandatory",
139: "Gross receipts/turnover in Sch BP but financial particulars (sundry creditors/inventories/debtors/cash-in-hand) not filled",
140: "ITR-4 filed (44AD/44AE/44ADA eligible) but no 44AD/44AE/44ADA income disclosed",
141: "Goods carriage owned/leased/hired > 12 months, or total holding period > 120 months",
142: "TDS credit claimed but corresponding receipts not offered to tax",
143: "Old regime: standard deduction 16(ia) max Rs 50,000",
144: "44AE presumptive income per vehicle < Rs 1,000/MT/month (tonnage>12MT) or Rs 7,500/month (tonnage<=12MT)",
145: "Old regime: 80CCD(1B) limited to Rs 50,000",
146: "Old regime: 80DD 'Dependent with disability' fixed at Rs 75,000",
147: "Old regime: 80DD 'Dependent with severe disability' fixed at Rs 1,25,000",
148: "Old regime, Sch Part BTI: 80DDB self+dependent > Rs 40,000",
149: "Old regime, Sch Part BTI: 80DDB senior-citizen self+dependent > Rs 1,00,000",
150: "Old regime, Sch Part BTI: 80EE > Rs 50,000",
151: "HRA u/s 10(13A) claimed => 80GG (rent >Rs 55,000 implied) not allowed",  # verbatim per source row 151
152: "Old regime: 80TTA max Rs 10,000",
153: "Old regime: 80TTB max Rs 50,000",
154: "Old regime, self-occupied: interest on borrowed capital > Rs 2,00,000",
155: "Old regime, employer category other than CG/SG/PSU/Others-Pensioners: 80CCD(1) max 10% of salary",
156: "Old regime: 80EEA > Rs 1,50,000",
157: "Old regime: 80EEA > 0 and 80EE > 0 (mutually exclusive)",
158: "Old regime: 80EEB > Rs 1,50,000",
159: "10(10B) first proviso compensation limit notified by CG cannot exceed Rs 5,00,000",
160: "Income details: allowance to extent exempt u/s 10 = sum of individual values entered",
161: "80CCD(2) claimed by employer category CG/SG/PSU/Others-Pensioners or 'not applicable'",
162: "89 relief claimed but salary and family pension details are zero/blank",
163: "80EEA claimed by HUF or Firm (other than LLP)",
164: "80EEB claimed by HUF or Firm (other than LLP)",
165: "Assessee HUF or Firm (other than LLP) and amount in Sch TDS1 > 0",
166: "Assessee HUF or Firm (other than LLP) and amount in salary details > 0",
167: "Original return filed u/s 142(1) cannot be revised",
168: "Old regime: Sch 80D Sl.1a Self&Family max Rs 25,000",
169: "Sch 80D Sl.1a = sum of Sl(i+ii)",
170: "Old regime: Sch 80D preventive health checkup (all fields combined) max Rs 5,000",
171: "Old regime: Sch 80D Sl.1b Self&Family(Senior) max Rs 50,000",
172: "Sch 80D Sl.1b = sum of Sl(i+ii+iii)",
173: "Old regime: Sch 80D Sl.2a Parents max Rs 25,000",
174: "Sch 80D Sl.2a = sum of Sl(i+ii)",
175: "Old regime: Sch 80D Sl.2b Parents(Senior) max Rs 50,000",
176: "Sch 80D Sl.2b = sum of Sl(i+ii+iii)",
177: "Old regime: Sch 80D Sl.3 eligible amount max Rs 1,00,000",
178: "Sch 80D Sl.3 = sum of Sl(1a+1b+2a+2b) restricted to GTI",
179: "Old regime: 80D claimed but details not provided in Sch 80D",
180: "Family pension income cannot be claimed by Firm (other than LLP) or HUF",
181: "10(10AA) claimed > Rs 25 lakh for employer category other than CG/SG/CG-Pensioners/SG-Pensioners",
182: "Old regime: 80U fixed Rs 1,25,000 for 'Self severe with disability'",
183: "New regime: Part C deductions all zero except 80CCD(2) and 80CCH",
184: "New regime: exempt allowances 10(5)/10(13A)/10(14)(i)/10(14)(ii) should not be more than 0",
185: "Sch Income Details total Dividend income = sum of quarterly breakup of dividend income",
186: "10(14)(ii) transport allowance for physically handicapped should not exceed Rs 38,400",
187: "Old regime: exempt allowances 10(14)(i) Rule 2BB(1)(a)-(c) / 10(14)(ii) transport-for-handicapped should not be more than 0",
188: "Once proceeding initiated u/s 148, original return u/s 139 cannot be revised",
189: "New regime: sum of 80C+80CCC+80CCD(1) should not exceed 0",
190: "New regime: 80G cannot be claimed, no details in Sch 80G",
191: "New regime: 80GG cannot be claimed, no details in Sch 80GG",
192: "New regime: 80TTA should not exceed 0",
193: "New regime: 80TTB should not exceed 0",
194: "New regime: 80U should not exceed 0",
195: "New regime: professional tax 16(iii) should not exceed 0",
196: "New regime: GTI = Business&Profession + Salary + HP + OS + LTCG112A",
197: "New regime, HP loss: GTI = Business&Profession + Salary + OS + LTCG112A",
198: "New regime: 10(5) LTC/LTA received should not exceed 0",
199: "New regime: 10(13A) HRA should not exceed 0",
200: "New regime: 10(14)(i) prescribed allowances should not exceed 0",
201: "New regime: 10(14)(ii) personal-expense allowances should not exceed 0",
202: "New regime: 10(17) MP/MLA/MLC allowance should not exceed 0",
203: "New regime: 80CCD(1B) should not exceed 0",
204: "New regime: 80DD should not exceed 0",
205: "New regime: 80DDB should not exceed 0",
206: "New regime: 80EE should not exceed 0",
207: "New regime, self-occupied: interest on borrowed capital should not exceed 0",
208: "New regime: 80CCD(1) should not exceed 0",
209: "New regime: 80EEA should not exceed 0",
210: "New regime: 80EEB should not exceed 0",
211: "New regime: 80D claimed should not exceed 0, no details in Sch 80D",
212: "HUF not eligible for 44ADA presumptive income",
213: "Sch BP: goods-carriage registration number should not repeat in 44AE",
214: "10(10B) first proviso / 10(10B) second proviso / 10(10C) cannot be claimed simultaneously",
215: "10(10CC) cannot exceed TDS claimed u/s 192 in Sch TDS1",
216: "Sch 80D Sl.1a Self&Family claimable only if dropdown at Sl.1 = No",
217: "Sch 80D Sl.1b Self&Family(Senior) claimable only if dropdown at Sl.1 = Yes",
218: "Sch 80D Sl.2a Parents claimable only if dropdown at Sl.2 = No",
219: "Sch 80D Sl.2b Parents(Senior) claimable only if dropdown at Sl.2 = Yes",
220: "Sch 80D: deduction cannot be claimed at Sl.1a/1b if dropdown = 'Not claiming for Self/Family'",
221: "Sch 80D: deduction cannot be claimed at Sl.2a/2b if dropdown = 'Not claiming for Parents'",
222: "Any nature-of-income dropdown cannot be selected more than once under Exempt Income",
223: "10(10B)(i)/(ii) not allowed to CG/SG employees, CG/SG/PSU/Other-Pensioners",
224: "80CCH deduction should not exceed 46.2% of Salary 17(1) to the extent of Rs 2,88,000",
225: "80CCH claimable only if nature of employment = Central Government and age 17-27 as on date of joining armed forces",
226: "10(10B) second proviso compensation cannot exceed Rs 5,00,000",
227: "Assessee with total income excl LTCG exceeding threshold cannot claim 87A rebate (marginal-relief note)",
228: "Details of Form 10-IEA mandatory if 'filed 10IEA within due date for earlier AY' = Yes",
229: "87A rebate max Rs 12,500 for total income up to Rs 5,00,000 under old regime",
230: "Firm eligible to claim VIA deductions under 80G and 80GGC only",
231: "HUF eligible to claim VIA deductions under 80G/80GGC/80D/80C/80DD/80DDB/80TTA only",
232: "HUF not eligible to claim Sl.2 (Parents) of Sch 80D",
233: "Exempt Allowances in Salary under each section should be disclosed in one dropdown",
234: "Due date of filing u/s 139(1) is 31 August of the AY unless extended",
235: "Tax regime fields not applicable for Firm; A23 fields greyed off by default",
236: "80D not applicable for Firm",
237: "44AD gross receipts > Rs 2 crore and cash receipts > 5% of total receipts => tax audit u/44AB mandatory, ITR-3/5 applicable",
238: "44ADA gross receipts > Rs 50,00,000 and cash receipts > 5% of total receipts => tax audit u/44AB mandatory, ITR-3/5 applicable",
239: "44ADA gross receipts Sl E3 should match sum of E3a+E3b+E3c",
240: "44AD gross receipts Sl E1 should match sum of E1a+E1b+E1c",
241: "80GGC claimed in Ch VI-A Income Details => same amount/details in Sch 80GGC",
242: "Sch 80GGC eligible amount per row = 'Donation in other mode' restricted to GTI",
243: "Sch 80GGC total donation = cash + other mode",
244: "Sch 80GGC Sl.D eligible amount = sum of individual amounts restricted to GTI",
245: "Sch 80GGC Sl.A/B/C = sum of individual amounts entered",
246: "Sch 80GGC: date of donation mandatory",
247: "Sch 80GGC: details of donation in other mode required",
248: "Sch VIA 80DD user value and system value must equal Sch 80DD Sl.ii value",
249: "Sch VIA 80U user value and system value must equal Sch 80U Sl.ii value",
250: "Sch 80DD: deduction > 0 => details of such donation required",
251: "Sch 80U: deduction > 0 => details of such donation required",
252: "Sch 80DD: deduction > 0 => Form 10IA details required",
253: "Sch 80U: deduction > 0 => Form 10IA details required",
254: "HUF can claim 80DD for dependent being 'Member of HUF'",
255: "Taxpayers with salary income must provide 'Nature of employment'",
256: "80GGC claimable only for contributions made between 01.04.2025-31.03.2026 (AY 2026-27)",
257: "Aadhaar number in Part A General Info must match Aadhaar per profile",
258: "Aadhaar number in Part A General Info must match Aadhaar per profile (dup)",
259: "Assessee must enter valid mobile number",
260: "Mandatory to select Option for 115BAC at A23 (Individual/HUF)",
261: "New regime: 57(iia) available up to 1/3rd of Family Pension, max Rs 25,000",
262: "New regime: standard deduction 16(ia) max Rs 75,000",
263: "New regime: 80CCD(2) <= 14% of salary if employer PSU/Others/Central Govt/State Govt",
264: "Assessee Firm (other than LLP): any A23 field with value for 10-IEA opt-out question",
265: "Sch EI Sl.iii LTCG u/s 112A > Rs 1,25,000",
266: "Sch EI Sl.iii LTCG u/s 112A should be output of Sl.(i-ii)",
267: "Total income excl LTCG u/s 112A > Rs 50 lakh",
268: "Part A General filing section 139(9) response inconsistent with A23 response of original ITR",
269: "Details of bank from which loan taken required for interest u/s 24(b)",
270: "80EE/80EEA claimable only when 24(b) limit is exhausted",
271: "80EE bank-loan details must be part of 24(b) schedule disclosure",
272: "80EEA bank-loan details must be part of 24(b) schedule disclosure",
273: "Sch 80C: nature of payment, eligible amount, policy/document identification number required",
274: "80E bank-loan details required in Sch 80E",
275: "80EE bank-loan details required in Sch 80EE",
276: "80EE claimable only if maximum loan taken does not exceed Rs 35 lakh against the property",
277: "80EEA bank-loan details required in Sch 80EEA",
278: "80EEA claimable only for residential property with stamp value up to Rs 45 lakh",
279: "Sch 80EEA: date of sanction of loan between 1.4.19 and 31.3.22",
280: "80EEB bank-loan details required in Sch 80EEB",
281: "Sch 80EEB: date of sanction of loan between 1.4.19 and 31.3.23",
282: "Form 10BA details required to claim 80GG",
283: "Sch 80D breakup rows for premium paid must match Health Insurance entered at Sl.1a",
284: "Sch 80D breakup rows for premium paid must match Health Insurance entered at Sl.1b",
285: "Sch 80D breakup rows for premium paid must match Health Insurance entered at Sl.2a",
286: "Sch 80D breakup rows for premium paid must match Health Insurance entered at Sl.2b",
287: "Form 10IA needs to be filed separately for 80U and 80DD respectively",
288: "Details of specified disease required to claim 80DDB",
289: "Sch House Property: interest on borrowed capital must equal Total interest paid u/s 24(b) per Sch 24(b)",
290: "80C in Ch VIA must match Total payment per Sch 80C",
291: "80E in Ch VIA must match Total interest paid per Sch 80E",
292: "80EE in Ch VIA must match Total interest paid per Sch 80EE",
293: "80EEA in Ch VIA must match Total interest paid per Sch 80EEA",
294: "80EEB in Ch VIA must match Total interest paid per Sch 80EEB",
295: "Sch 24(b) sum of individual 'Interest paid during the year' rows = Total of Payments",
296: "Sch 80C sum of individual 'Amount of payment' rows = Total of Payments",
297: "Sch 80E sum of individual 'Amount of interest paid' rows = Total of Payments",
298: "Sch 80EE sum of individual 'Interest paid during the year' rows = Total of Payments",
299: "Sch 80EEA sum of individual 'Amount of interest paid' rows = Total of Payments",
300: "Sch 80EEB sum of individual 'Amount of interest paid' rows = Total of Payments",
301: "Sch 80EE: date of sanction of loan between 1.4.16 and 31.3.17",
302: "New regime, self-occupied: interest on borrowed capital not allowed",
303: "Firm not eligible to fill 80C/80E/80EE/80EEA/80EEB/10(13A) schedules",
304: "HUF not eligible to fill 80CCC/80E/80EE/80EEA/80EEB schedules",
305: "Individual opting new regime and filled 80C/80E/80EE/80EEA/80EEB/10(13A) schedules",
306: "Sch 80D Sl.1a(i): insurer name, policy number required",
307: "Sch 80D Sl.1b(i): insurer name, policy number required",
308: "Sch 80D Sl.2a(i): insurer name, policy number, receipt/document number required",
309: "Sch 80D Sl.2b(i): insurer name, policy number required",
310: "TDS2(i)/(ii) dropdown section 192 (salary) is invalid for other-than-salary schedule",
311: "10(13A) HRA cannot exceed Actual rent paid minus 10% of basic salary+DA",
312: "10(13A) HRA cannot exceed 50% of basic salary+DA",
313: "Sch 10(13A) HRA exemption = lowest of (actual HRA received, rent paid-10% salary+DA, 40/50% salary+DA)",
314: "Taxpayers with salary income and exempt allowances must provide Nature of employment",
315: "Sch 10(13A) needs to be filled for claiming exempt allowance u/s 10(13A)",
316: "Sum of basic salary+DA (Sch 10(13A)) and actual HRA received cannot exceed Salary 17(1)",
317: "10(10) gratuity cannot exceed Rs 25,00,000 if nature of employment CG/CG-Pensioners/SG/SG-Pensioners",
318: "Firm or HUF with date of formation on/after 01/04/2026 cannot file return for AY 26-27",
319: "Status Individual with date of formation on/after 01/04/2008 shall not be allowed to file for AY 25-26",
320: "Exempt Allowance 10(13A) in Sch Salary must match Eligible allowance u/s 10(13A) per Sch 10(13A)",
321: "Based on A23 response, taxpayer shall respond to only one applicable question A23A or A23B",
322: "Exempt income received by judge under Supreme/High Court Judges Act can only be claimed by CG/SG employees",
323: "Type of house property mandatory if interest on borrowed capital u/s 24(b) claimed",
324: "Eligible amount of deduction u/s 80C should not exceed user-enterable amount",
325: "Eligible amount of deduction u/s 80CCC should not exceed user-enterable amount",
326: "Eligible amount of deduction u/s 80CCD(1) should not exceed user-enterable amount",
327: "Eligible amount of deduction u/s 80CCD(1B) should not exceed user-enterable amount",
328: "Eligible amount of deduction u/s 80CCD(2) should not exceed user-enterable amount",
329: "Eligible amount of deduction u/s 80D should not exceed user-enterable amount",
330: "Eligible amount of deduction u/s 80DD should not exceed user-enterable amount",
331: "Eligible amount of deduction u/s 80DDB should not exceed user-enterable amount",
332: "Eligible amount of deduction u/s 80E should not exceed user-enterable amount",
333: "Eligible amount of deduction u/s 80EE should not exceed user-enterable amount",
334: "Eligible amount of deduction u/s 80EEA should not exceed user-enterable amount",
335: "Eligible amount of deduction u/s 80EEB should not exceed user-enterable amount",
336: "Eligible amount of deduction u/s 80G should not exceed user-enterable amount",
337: "Eligible amount of deduction u/s 80GG should not exceed user-enterable amount",
338: "Eligible amount of deduction u/s 80GGC should not exceed user-enterable amount",
339: "Eligible amount of deduction u/s 80TTA should not exceed user-enterable amount",
340: "Eligible amount of deduction u/s 80TTB should not exceed user-enterable amount",
341: "Eligible amount of deduction u/s 80U should not exceed user-enterable amount",
342: "Eligible amount of deduction u/s 80CCH should not exceed user-enterable amount",
343: "LTCG u/s 112A = GTI including LTCG minus GTI excluding LTCG",
344: "Part A General: representative's name/email/contact mandatory if verification capacity = Representative",
345: "If return filed by representative assessee (flag Y), details must be provided",
346: "Co-owned property: total of assessee's share and co-owners' share = 100%",
347: "Sch HP co-owned property: Annual value owned = own% share * Annual value",
348: "Assessee share of co-owned property is zero => interest on borrowed capital cannot exceed zero",
349: "Sch HP Sl.1d Total = output of Sl(1b+1c)",
350: "Sch HP Sl.1i Total = output of Sl(1g+1h)",
351: "Co-owned house property: assessee PAN & co-owner's PAN cannot be same",
352: "Gross rent received/lettable value is zero/null and 'rent which cannot be realized' > 0",
353: "A23 'filed 10IEA within due date for earlier AY' = Yes => A(i) and A(ii) mandatory",
354: "A23 'filed 10IEA within due date for earlier AY' = No => A23(B) mandatory",
355: "A23(A)(ii) re-entered new regime via 10IEA = Yes => A23(A)(ii)(a) mandatory",
356: "A23(A)(ii) re-entered new regime via 10IEA = No => A23(A)(ii)(b) mandatory",
357: "A23(A)(ii)(b) furnished 10IEA for re-entering = Yes => A23(A)(ii)(b)(i) mandatory",
358: "A23(A)(ii)(b) furnished 10IEA for re-entering = No => A23(A)(ii)(b)(i) not applicable",
359: "A23(B) furnished 10IEA within due date for current AY = Yes => A23(B)(i) mandatory",
360: "A23(B) furnished 10IEA within due date for current AY = No => A23(B)(i) not applicable",
361: "Form 10IEA details filled in A23(B)(i) => A23(B) cannot be blank",
362: "Form 10IEA details filled in A23(A)(ii)(b)(i) => A23(A)(ii)(b) cannot be blank",
363: "Details filled in A23(A)(ii)(a) or A(ii)(b) => A23(A)(ii) cannot be blank",
364: "Details filled in A23(A)(i) or A(ii) => A23(A) cannot be blank",
365: "New regime: judge's exempt salary income cannot exceed 0",
366: "80CCC: sum of individual rows for 'Amount' must equal Total 'Amounts' at field 80CCC in Income Details",
367: "Sec 10(2) member's share from HUF dropdown cannot be selected >1 time",
368: "Sec 10(10BB) Bhopal Gas Leak Disaster payments dropdown cannot be selected >1 time",
369: "Sec 10(11A) Sukanya Samriddhi Yojana receipt dropdown cannot be selected >1 time",
370: "Sec 10(12A) NPS partial withdrawal dropdown cannot be selected >1 time",
371: "Sec 10(12AA) NPS Trust payment dropdown cannot be selected >1 time",
372: "Sec 10(12AB) notified lump-sum receipt dropdown cannot be selected >1 time",
373: "Sec 10(12B) NPS lump sum at exit/closure dropdown cannot be selected >1 time",
374: "Sec 10(12BA) NPS partial withdrawal dropdown cannot be selected >1 time",
375: "Sec 10(12C) Agniveer Corpus Fund income dropdown cannot be selected >1 time",
376: "Sec 10(15) interest on specified securities/investments dropdown cannot be selected >1 time",
377: "Sec 10(19A) ex-ruler palace annual value dropdown cannot be selected >1 time",
378: "Sec 10(23AA) armed-forces fund receipt dropdown cannot be selected >1 time",
379: "Contributions received from recognized stock exchange dropdown cannot be selected >1 time",
380: "Sec 10(23FBB) investment-fund income dropdown cannot be selected >1 time",
381: "Sec 10(23FD) business-trust income dropdown cannot be selected >1 time",
382: "Sec 10(25) approved superannuation/gratuity/pension-fund receipt dropdown cannot be selected >1 time",
383: "Sec 10(25A) Employees' State Insurance Fund income dropdown cannot be selected >1 time",
384: "Sec 10(30) subsidy from Tea Board dropdown cannot be selected >1 time",
385: "Sec 10(31) Rubber/Coffee/Tea development accounts/funds dropdown cannot be selected >1 time",
386: "Minor child's income small exemption dropdown cannot be selected >1 time",
387: "Sec 10(35) specified mutual-fund income dropdown cannot be selected >1 time",
388: "Sec 10(35A) securitisation-trust income dropdown cannot be selected >1 time",
389: "Sec 10(43) reverse-mortgage receipt dropdown cannot be selected >1 time",
390: "Sec 10(44) NPS Trust income dropdown cannot be selected >1 time",
391: "New regime: exempt income u/s 10(32) minor child's income should not exceed 0",
392: "Fees for furnishing revised return u/234I = Rs 1,000 if filed after 31/12/2026, s.139(5), income<=5L",
393: "AY selected in A23(A)(ii)(a) shall not be same or prior to AY selected in A23(A)(i)",
394: "IFSC and UPI/cheque/IMPS/NEFT/RTGS reference number mandatory in Sch 80G for non-cash donation",
395: "PAN of donee mandatory if donation amount > 0 in Sch 80G",
396: "Old regime: Sch 80G multiple cash entries same PAN, aggregate<=2000 => eligible restricted to min(2000, claimed)",
397: "Fees for furnishing revised return u/234I = Rs 5,000 if filed after 31/12/2026, s.139(5), income>5L",
398: "Name and PAN of political party necessary to claim 80GGC",
399: "Sch 80G: either cash donation or donation in other mode shall be entered per row, not both",
402: "PRAN should be provided in Sch VIA to claim 80CCD(1) or 80CCD(1B)",
403: "Part A General: representative's email/contact must not match taxpayer's email/contact",
404: "Property not co-owned: assessee's share must equal 100%",
405: "Sch HP co-owned=Yes: other co-owner(s) % share must be > 0 and < 100%",
406: "Sch HP co-owned=Yes: assessee's % share must be < 100%",
407: "PRAN entered but amount in 80CCD(1) and 80CCD(1B) is 0",
408: "'Rent which cannot be realized' cannot exceed Gross rent received/lettable value",
409: "80CCC > 0 => mandatory to add >=1 row with Type of identifier/Identifier No./Amount",
410: "Secondary Address in Part A General Info mandatory to be provided",
411: "Secondary address should not be same as Primary address if 'No' for 'is secondary same as primary'",
}

CATEGORY_B = {
1: "Income chargeable under business = sum of income offered under presumptive 44AD/44ADA/44AE",
2: "TDS deducted in Sch TDS1 cannot exceed value in Sch Salary Sl.2 Total Gross Salary",
3: "Aadhaar-PAN linking required per Circular 03/2023",
4: "Aadhaar quoting u/s 139(AA) required + linking per Circular 03/2023",
5: "Nil return filer requested to check AIS/26AS before proceeding",
6: "TDS2(i) section code 194B/194BB/194BA/194IA/194IC/194LA/194S, or special-rate income not ITR-4 eligible",
7: "TDS2(ii) section code same set as #6, or special-rate income not ITR-4 eligible",
8: "TDS2(i) section code 194E/194LB/194LC/194LBA(a/b/c)/195/196A/196B/196C/196D/196D(1A)",
9: "TDS2(ii) section code same set as #8",
10: "Form 10IEA in DB => AY/date of filing/acknowledgement number must match DB",
11: "Form 10IEA shall be filed within due date for opting out or re-entering for current AY",
12: "Form 10IEA not filed previously but details entered in ITR",
13: "Form 10IEA not filed for current AY but details entered in ITR",
}

CATEGORY_D = {
1: "Relief u/s 89(1) claimed without furnishing Form 10E",
2: "80GG can be claimed only up to Rs 5,000/month (max 12 months) or rent actually paid, whichever is lower",
}
