"""ITD's bespoke foreign-country code list, used by ``CountryCodeExcludingIndia``
across every ITR-2 schedule that discloses a foreign country (Schedule FA,
Schedule FSI, Schedule TR, Schedule OS's DTAA block).

This is NOT ISO 3166 (alpha or numeric) -- it is a specific enum ITD defines
in the official JSON schema itself, transcribed here verbatim from
``Reference Docs by CBDT & ITD/Official JSON Schema/ITR-2_2026_Main_V1.1``'s
``CountryCodeExcludingIndia`` definition (249 entries; India is excluded by
design, since every schedule using this code is for a taxpayer's FOREIGN
holdings/income). Confirmed against that definition's own ``enum`` list, not
just its ``description`` text.

Before this module existed, every builder that needed a foreign country
disclosure passed the same raw ``country_code`` input value into BOTH
``CountryName`` (a free-text name) and ``CountryCodeExcludingIndia`` (this
enum) -- correct for the latter only if the caller already supplies one of
these exact codes, and never correct for the former, which needs a real
name. See ``Docs/ITR2_FRONTEND_AND_SERIALIZATION_AUDIT_AY2026_27.md`` §10.2
for the full evidence trail across the affected builders.
"""

from __future__ import annotations

ITD_COUNTRY_CODE_TO_NAME: dict[str, str] = {
    "1": "CANADA",
    "2": "UNITED STATES OF AMERICA",
    "5": "ITALY",
    "6": "HOLY SEE",
    "7": "KAZAKHSTAN",
    "8": "RUSSIAN FEDERATION",
    "9": "CHRISTMAS ISLAND",
    "14": "PORTUGAL",
    "15": "NORFOLK ISLAND",
    "20": "EGYPT",
    "28": "SOUTH AFRICA",
    "30": "GREECE",
    "31": "NETHERLANDS",
    "32": "BELGIUM",
    "33": "FRANCE",
    "35": "SPAIN",
    "36": "HUNGARY",
    "40": "ROMANIA",
    "41": "SWITZERLAND",
    "43": "AUSTRIA",
    "44": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
    "45": "DENMARK",
    "46": "SWEDEN",
    "47": "NORWAY",
    "48": "POLAND",
    "49": "GERMANY",
    "51": "PERU",
    "52": "MEXICO",
    "53": "CUBA",
    "54": "ARGENTINA",
    "55": "BRAZIL",
    "56": "CHILE",
    "57": "COLOMBIA",
    "58": "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    "60": "MALAYSIA",
    "61": "AUSTRALIA",
    "62": "INDONESIA",
    "63": "PHILIPPINES",
    "64": "NEW ZEALAND",
    "65": "SINGAPORE",
    "66": "THAILAND",
    "81": "JAPAN",
    "82": "KOREA (REPUBLIC OF)",
    "84": "VIET NAM",
    "86": "CHINA",
    "90": "TURKEY",
    "92": "PAKISTAN",
    "93": "AFGHANISTAN",
    "94": "SRI LANKA",
    "95": "MYANMAR",
    "98": "IRAN (ISLAMIC REPUBLIC OF)",
    "211": "SOUTH SUDAN",
    "212": "MOROCCO",
    "213": "ALGERIA",
    "216": "TUNISIA",
    "218": "LIBYA",
    "220": "GAMBIA",
    "221": "SENEGAL",
    "222": "MAURITANIA",
    "223": "MALI",
    "224": "GUINEA",
    "225": "CÔTE D'IVOIRE",
    "226": "BURKINA FASO",
    "227": "NIGER",
    "228": "TOGO",
    "229": "BENIN",
    "230": "MAURITIUS",
    "231": "LIBERIA",
    "232": "SIERRA LEONE",
    "233": "GHANA",
    "234": "NIGERIA",
    "235": "CHAD",
    "236": "CENTRAL AFRICAN REPUBLIC",
    "237": "CAMEROON",
    "238": "CABO VERDE",
    "239": "SAO TOME AND PRINCIPE",
    "240": "EQUATORIAL GUINEA",
    "241": "GABON",
    "242": "CONGO",
    "243": "CONGO (DEMOCRATIC REPUBLIC OF THE)",
    "244": "ANGOLA",
    "245": "GUINEA-BISSAU",
    "248": "SEYCHELLES",
    "249": "SUDAN",
    "250": "RWANDA",
    "251": "ETHIOPIA",
    "252": "SOMALIA",
    "253": "DJIBOUTI",
    "254": "KENYA",
    "255": "TANZANIA, UNITED REPUBLIC OF",
    "256": "UGANDA",
    "257": "BURUNDI",
    "258": "MOZAMBIQUE",
    "260": "ZAMBIA",
    "261": "MADAGASCAR",
    "262": "RÉUNION",
    "263": "ZIMBABWE",
    "264": "NAMIBIA",
    "265": "MALAWI",
    "266": "LESOTHO",
    "267": "BOTSWANA",
    "268": "SWAZILAND",
    "269": "MAYOTTE",
    "270": "COMOROS",
    "290": "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    "291": "ERITREA",
    "297": "ARUBA",
    "298": "FAROE ISLANDS",
    "299": "GREENLAND",
    "350": "GIBRALTAR",
    "352": "LUXEMBOURG",
    "353": "IRELAND",
    "354": "ICELAND",
    "355": "ALBANIA",
    "356": "MALTA",
    "357": "CYPRUS",
    "358": "FINLAND",
    "359": "BULGARIA",
    "370": "LITHUANIA",
    "371": "LATVIA",
    "372": "ESTONIA",
    "373": "MOLDOVA (REPUBLIC OF)",
    "374": "ARMENIA",
    "375": "BELARUS",
    "376": "ANDORRA",
    "377": "MONACO",
    "378": "SAN MARINO",
    "380": "UKRAINE",
    "381": "SERBIA",
    "382": "MONTENEGRO",
    "385": "CROATIA",
    "386": "SLOVENIA",
    "387": "BOSNIA AND HERZEGOVINA",
    "389": "MACEDONIA(THE FORMER YUGOSLAV REPUBLIC OF)",
    "420": "CZECHIA",
    "421": "SLOVAKIA",
    "423": "LIECHTENSTEIN",
    "500": "FALKLAND ISLANDS (MALVINAS)",
    "501": "BELIZE",
    "502": "GUATEMALA",
    "503": "EL SALVADOR",
    "504": "HONDURAS",
    "505": "NICARAGUA",
    "506": "COSTA RICA",
    "507": "PANAMA",
    "508": "SAINT PIERRE AND MIQUELON",
    "509": "HAITI",
    "590": "GUADELOUPE",
    "591": "BOLIVIA (PLURINATIONAL STATE OF)",
    "592": "GUYANA",
    "593": "ECUADOR",
    "594": "FRENCH GUIANA",
    "595": "PARAGUAY",
    "596": "MARTINIQUE",
    "597": "SURINAME",
    "598": "URUGUAY",
    "670": "TIMOR-LESTE\xa0(EAST TIMOR)",
    "672": "COCOS (KEELING) ISLANDS",
    "673": "BRUNEI DARUSSALAM",
    "674": "NAURU",
    "675": "PAPUA NEW GUINEA",
    "676": "TONGA",
    "677": "SOLOMON ISLANDS",
    "678": "VANUATU",
    "679": "FIJI",
    "680": "PALAU",
    "681": "WALLIS AND FUTUNA",
    "682": "COOK ISLANDS",
    "683": "NIUE",
    "684": "AMERICAN SAMOA",
    "685": "SAMOA",
    "686": "KIRIBATI",
    "687": "NEW CALEDONIA",
    "688": "TUVALU",
    "689": "FRENCH POLYNESIA",
    "690": "TOKELAU",
    "691": "MICRONESIA (FEDERATED STATES OF)",
    "692": "MARSHALL ISLANDS",
    "850": "KOREA(DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    "852": "HONG KONG",
    "853": "MACAO",
    "855": "CAMBODIA",
    "856": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    "880": "BANGLADESH",
    "886": "TAIWAN",
    "960": "MALDIVES",
    "961": "LEBANON",
    "962": "JORDAN",
    "963": "SYRIAN ARAB REPUBLIC",
    "964": "IRAQ",
    "965": "KUWAIT",
    "966": "SAUDI ARABIA",
    "967": "YEMEN",
    "968": "OMAN",
    "970": "PALESTINE, STATE OF",
    "971": "UNITED ARAB EMIRATES",
    "972": "ISRAEL",
    "973": "BAHRAIN",
    "974": "QATAR",
    "975": "BHUTAN",
    "976": "MONGOLIA",
    "977": "NEPAL",
    "992": "TAJIKISTAN",
    "993": "TURKMENISTAN",
    "994": "AZERBAIJAN",
    "995": "GEORGIA",
    "996": "KYRGYZSTAN",
    "998": "UZBEKISTAN",
    "1001": "ÅLAND ISLANDS",
    "1002": "BONAIRE, SINT EUSTATIUS AND SABA",
    "1003": "BOUVET ISLAND",
    "1004": "FRENCH SOUTHERN TERRITORIES",
    "1005": "HEARD ISLAND AND MCDONALD ISLANDS",
    "1006": "SAINT BARTHÉLEMY",
    "1007": "SAINT MARTIN (FRENCH PART)",
    "1008": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    "1009": "UNITED STATES MINOR OUTLYING ISLANDS",
    "1010": "ANTARCTICA",
    "1011": "PITCAIRN",
    "1012": "SVALBARD AND JAN MAYEN",
    "1013": "WESTERN SAHARA",
    "1014": "BRITISH INDIAN OCEAN TERRITORY",
    "1015": "CURAÇAO",
    "1242": "BAHAMAS",
    "1246": "BARBADOS",
    "1264": "ANGUILLA",
    "1268": "ANTIGUA AND BARBUDA",
    "1284": "VIRGIN ISLANDS (BRITISH)",
    "1340": "VIRGIN ISLANDS (U.S.)",
    "1345": "CAYMAN ISLANDS",
    "1441": "BERMUDA",
    "1473": "GRENADA",
    "1481": "GUERNSEY",
    "1534": "JERSEY",
    "1624": "ISLE OF MAN",
    "1649": "TURKS AND CAICOS ISLANDS",
    "1664": "MONTSERRAT",
    "1670": "NORTHERN MARIANA ISLANDS",
    "1671": "GUAM",
    "1721": "SINT MAARTEN (DUTCH PART)",
    "1758": "SAINT LUCIA",
    "1767": "DOMINICA",
    "1784": "SAINT VINCENT AND THE GRENADINES",
    "1787": "PUERTO RICO",
    "1809": "DOMINICAN REPUBLIC",
    "1868": "TRINIDAD AND TOBAGO",
    "1869": "SAINT KITTS AND NEVIS",
    "1876": "JAMAICA",
    "9999": "OTHERS",
}


def country_name(code: str) -> str:
    """Look up the official ITD country name for a ``CountryCodeExcludingIndia``
    code. Raises ``ValueError`` (naming the bad code) rather than fabricating
    a name for an unrecognized value -- this is a closed, official enum, not
    a free-text field, so an unrecognized code is a genuine input error, not
    a case to guess through."""
    try:
        return ITD_COUNTRY_CODE_TO_NAME[code]
    except KeyError:
        raise ValueError(
            f"{code!r} is not a valid ITD CountryCodeExcludingIndia code. "
            "See app/engine/itd/country_codes.py for the full official list."
        ) from None
