"""Mode-and-form-agnostic ERI UAT sanity pack generator.

Replaces the ITR-1/ITR-4-only, Type-3-only ``scripts/type3_uat_sanity.py``.
See ``Docs/ERI_UAT_EXPANSION_PLAN.md`` (Phase 1) for the design rationale.

Produces CBDT-compliant ITR JSONs for each registered form, using the ERI
credential bundle resolved from the process environment (``ERI_MODE`` /
``ERI_ENV`` — see the Phase 0 decision below), runs the full CBDT Category A
+ schema validators, and writes a manifest describing each generated JSON's
SW_ID, Digest, and schema status — ready to email to
``erihelp@incometax.gov.in`` for the ITD UAT sanity check.

Phase 0 decision (credential switching): this script never mutates ``.env``
and ``app/eri/config.py`` has no mode-override mechanism. Instead, the
caller sets ``ERI_MODE``/``ERI_ENV`` as process environment variables for a
single invocation, and this script's ``load_dotenv()`` call deliberately
omits ``override=True`` so a shell-set value wins over whatever ``.env`` has
stored. Each mode is generated by a fully separate OS process:

    ERI_MODE=type3 ERI_ENV=uat python scripts/eri_uat_sanity.py --mode type3 --forms ITR-1 ITR-4
    ERI_MODE=type2 ERI_ENV=uat python scripts/eri_uat_sanity.py --mode type2 --forms ITR-1 ITR-4

``--mode`` is not read for credential resolution (``get_eri_credentials()``
always resolves from the process environment, exactly as every other ERI
call site does) — it is used only to (a) name the output directory / label
the manifest, and (b) assert the resolved bundle actually matches what the
operator asked for, so a forgotten ``ERI_MODE=`` prefix fails loudly instead
of silently generating the wrong bundle.

The generated JSONs carry the REAL SW_ID for the resolved bundle + a REAL
44-char HMAC-SHA256 Digest (computed over the full document by
:mod:`app.eri.digest`), so they are the exact artefacts the ITD UAT
portal would receive. No taxpayer PII is in any fixture — these are
synthetic maximally-populated drafts (or seeded from the ITD-provided test
data sheet where a form's draft builder does so).

Forms without a registered draft-variant builder yet (ITR-2/3/5/6/7 until
their respective plan phases land) are reported as "pending" in the
manifest rather than causing the whole run to fail, so the manifest always
shows the ITD team the full intended scope.

Usage:
    ERI_MODE=type3 ERI_ENV=uat python scripts/eri_uat_sanity.py
    ERI_MODE=type3 ERI_ENV=uat python scripts/eri_uat_sanity.py --mode type3 --output-dir sanity_out
    ERI_MODE=type2 ERI_ENV=uat python scripts/eri_uat_sanity.py --mode type2 --forms ITR-1 ITR-4
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Callable

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Load .env BEFORE any app import that reads os.environ — the Digest and
# SW_ID must flow from the active credential bundle. Deliberately NOT
# override=True (Phase 0 decision, ERI_UAT_EXPANSION_PLAN.md): a shell-set
# ERI_MODE/ERI_ENV must win over whatever .env has stored, so the two
# separate-process invocations documented above reliably select different
# bundles without ever touching the .env file on disk.
from dotenv import load_dotenv

load_dotenv(ROOT / ".env")

from app.eri.config import get_eri_credentials
from app.eri.digest import compute_digest
from app.engine.common.due_dates import applicable_filing_section
from app.engine.filing_gateway_v2 import FilingGatewayV2Error, generate_cbdt_json

DraftVariant = tuple[str, Any]  # (label, ReturnDraft)
FormVariantBuilder = Callable[[], list[DraftVariant]]

# Registry of form -> builder returning [(label, ReturnDraft), ...]. Each
# form's plan phase adds its own registration in _load_builtin_registrations
# below instead of the generation loop hardcoding an if/elif chain per form.
_FORM_VARIANT_BUILDERS: dict[str, FormVariantBuilder] = {}


def _register_form_variants(form: str, builder: FormVariantBuilder) -> None:
    """Register the draft-variant builder for ``form``."""
    _FORM_VARIANT_BUILDERS[form] = builder


def _load_builtin_registrations() -> None:
    """Register every form that currently has a draft-variant builder.

    Imported lazily (inside a function, not at module scope) so the script's
    own ``--help`` works even if a future form's builder module has an
    import-time error — the failure surfaces when that form is actually
    requested, not for every invocation.
    """
    if _FORM_VARIANT_BUILDERS:
        return  # already loaded (e.g. called twice in one process)

    from audit_itr_coverage import build_full_itr1_draft, build_full_itr4_draft

    # build_full_itr1_draft branches on "80EE" (see audit_itr_coverage.py:247);
    # "80EEB" matched no branch and silently produced a second copy of the
    # 80EEA draft, so the pack shipped one file twice and lost the senior-
    # citizen 80D arrays that the 80EE variant is there to exercise.
    _register_form_variants(
        "ITR-1",
        lambda: [
            ("default_80EEA", build_full_itr1_draft(loan_variant="80EEA")),
            ("senior_80EE", build_full_itr1_draft(loan_variant="80EE")),
        ],
    )
    _register_form_variants(
        "ITR-4",
        lambda: [
            ("44AD", build_full_itr4_draft(scheme="44AD", loan_variant="80EEA")),
            ("44ADA", build_full_itr4_draft(scheme="44ADA", loan_variant="80EEA")),
            ("44AE", build_full_itr4_draft(scheme="44AE", loan_variant="80EEA")),
        ],
    )
    # ITR-2, ITR-3, ITR-5, ITR-6, ITR-7: not yet registered. Each is added
    # here by its own plan phase (Docs/ERI_UAT_EXPANSION_PLAN.md Phases 6,
    # 11, 14, 15, 16) once that form's v2 pipeline + validators exist.


def _form_variants(form: str) -> list[DraftVariant]:
    """Return the ``(label, ReturnDraft)`` variants for ``form``.

    Raises:
        ValueError: If no builder is registered for ``form`` yet — caught by
            the caller and reported as "pending" in the manifest.
    """
    _load_builtin_registrations()
    builder = _FORM_VARIANT_BUILDERS.get(form)
    if builder is None:
        raise ValueError(f"No sanity variants registered for {form} yet.")
    return builder()


def _apply_current_filing_section(draft: Any) -> Any:
    """Stamp the filing section that actually applies on the day of generation.

    The fixtures are pinned to 139(1), which stops being valid once the
    form's due date passes. The pack is meant to be the exact artefact the
    portal would receive, and a return filed today after the due date is
    belated under 139(4), so derive it rather than hardcode it.
    """
    section = applicable_filing_section(draft.form, draft.assessmentYear or "2026-27")
    draft.filing.filingSection = section
    return draft


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 for the manifest."""
    return datetime.now(UTC).isoformat(timespec="seconds")


def _summarize_json(form: str, official: dict) -> dict[str, Any]:
    """Extract the CreationInfo + a present-path count for the manifest."""
    form_key = form.replace("-", "")
    ci = official["ITR"][form_key]["CreationInfo"]
    return {
        "sw_created_by": ci.get("SWCreatedBy"),
        "json_created_by": ci.get("JSONCreatedBy"),
        "digest": ci.get("Digest"),
        "digest_length": len(str(ci.get("Digest", ""))),
        "json_creation_date": ci.get("JSONCreationDate"),
    }


def _digest_round_trips(form: str, official: dict) -> bool:
    """Verify the stamped Digest recomputes over the full document."""
    try:
        form_key = form.replace("-", "")
        stamped = official["ITR"][form_key]["CreationInfo"]["Digest"]
        recomputed = compute_digest(official)
        return recomputed == stamped
    except Exception:
        return False


def generate_sanity_pack(
    forms: list[str],
    output_dir: Path,
    mode: str,
) -> dict[str, Any]:
    """Generate one JSON per ``(form, variant)`` and a manifest summary.

    Args:
        forms: Forms to generate (e.g. ``["ITR-1", "ITR-4"]``).
        output_dir: Directory to write the JSONs and manifest into.
        mode: The ERI mode the caller asked for (``"type2"`` or
            ``"type3"``) — asserted against what ``get_eri_credentials()``
            actually resolves from the process environment, so a forgotten
            ``ERI_MODE=`` prefix fails loudly instead of silently generating
            the wrong bundle.

    Returns:
        The manifest dict (also written to ``sanity_manifest.json``).

    Raises:
        SystemExit: If the resolved credential mode doesn't match ``mode``.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    creds = get_eri_credentials()
    if creds.mode != mode:
        raise SystemExit(
            f"--mode {mode!r} was requested but the process environment "
            f"resolved ERI_MODE={creds.mode!r}. Set ERI_MODE={mode!r} (and "
            "ERI_ENV) before invoking this script - see the module "
            "docstring for the two-invocation usage pattern. Refusing to "
            "generate a pack under the wrong credential bundle."
        )

    manifest: dict[str, Any] = {
        "generated_at": _now_iso(),
        "eri_mode": creds.mode,
        "eri_environment": creds.environment,
        "sw_id": creds.sw_id,
        "digest_iterations": creds.digest_iterations,
        "forms": [],
        "notes": [
            "All JSONs are synthetic maximally-populated drafts (or seeded",
            "from the ITD-provided test-data sheet where noted) — no",
            "taxpayer PII.",
            f"Each JSON carries the real {creds.mode}/{creds.environment} SW_ID",
            "+ a real 44-char HMAC-SHA256 Digest computed by app/eri/digest.py",
            "over the complete ITR document.",
            "Ready to submit to erihelp@incometax.gov.in for the ITD UAT",
            "sanity check.",
        ],
    }

    for form in forms:
        form_entry: dict[str, Any] = {"form": form, "variants": []}
        try:
            variants = _form_variants(form)
        except ValueError as exc:
            form_entry["status"] = "pending"
            form_entry["reason"] = str(exc)
            manifest["forms"].append(form_entry)
            continue

        for label, draft in variants:
            draft = _apply_current_filing_section(draft)
            variant_entry: dict[str, Any] = {
                "label": label,
                "mode": creds.mode,
                "filing_section": draft.filing.filingSection,
            }
            try:
                official, _summary = generate_cbdt_json(draft)
            except FilingGatewayV2Error as exc:
                variant_entry["status"] = "schema_failed"
                variant_entry["errors"] = list(exc.errors)[:10]
                form_entry["variants"].append(variant_entry)
                continue

            fname = f"{form}_{label}_{creds.mode}_AY{draft.assessmentYear}.json"
            fpath = output_dir / fname
            fpath.write_text(
                json.dumps(official, indent=2, default=str), encoding="utf-8"
            )
            variant_entry["status"] = "generated"
            variant_entry["file"] = fname
            variant_entry.update(_summarize_json(form, official))
            variant_entry["digest_round_trips"] = _digest_round_trips(form, official)
            form_entry["variants"].append(variant_entry)

        form_entry["status"] = (
            "generated" if all(v.get("status") == "generated" for v in form_entry["variants"])
            else "partial"
        )
        manifest["forms"].append(form_entry)

    manifest_path = output_dir / "sanity_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    return manifest


def main() -> int:
    """CLI entry: parse args, generate the sanity pack, print the manifest."""
    parser = argparse.ArgumentParser(
        description="Generate an ERI UAT sanity pack (ITR JSONs + manifest) for one mode.",
    )
    parser.add_argument(
        "--mode",
        choices=["type2", "type3"],
        default="type3",
        help=(
            "ERI mode this pack is for (default: type3). Must match ERI_MODE "
            "in the process environment — see the module docstring."
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory to write the JSONs and manifest into "
        "(default: downloads/<mode>_uat_sanity).",
    )
    parser.add_argument(
        "--forms",
        nargs="+",
        default=["ITR-1", "ITR-4"],
        help="Forms to generate (default: ITR-1 ITR-4; ITR-2/3/5/6/7 pending "
        "their plan phases).",
    )
    args = parser.parse_args()

    output_dir = Path(
        args.output_dir or (ROOT / "downloads" / f"{args.mode}_uat_sanity")
    ).resolve()
    print(f"[sanity] mode: {args.mode}")
    print(f"[sanity] output dir: {output_dir}")
    print(f"[sanity] forms: {args.forms}")
    manifest = generate_sanity_pack(args.forms, output_dir, args.mode)

    print(f"\n[sanity] SW_ID: {manifest['sw_id']}  ({manifest['eri_mode']}/{manifest['eri_environment']})")
    print(f"[sanity] digest iterations: {manifest['digest_iterations']}")
    for form_entry in manifest["forms"]:
        status = form_entry["status"]
        print(f"\n  {form_entry['form']}: {status}")
        if status == "pending":
            print(f"    reason: {form_entry.get('reason')}")
            continue
        for v in form_entry["variants"]:
            if v["status"] == "generated":
                print(
                    f"    [{v['label']}] {v['file']}  "
                    f"digest={v['digest'][:24]}...  "
                    f"round_trips={v['digest_round_trips']}"
                )
            else:
                print(f"    [{v['label']}] {v['status']}  errors={v.get('errors')}")
    print(f"\n[sanity] manifest: {output_dir / 'sanity_manifest.json'}")
    print(
        "[sanity] Email the JSONs + manifest to erihelp@incometax.gov.in "
        "for the ITD UAT sanity check."
    )
    # Non-zero exit if any form failed, so CI / the operator notices.
    all_ok = all(
        f["status"] in ("generated", "pending") and f["status"] != "partial"
        for f in manifest["forms"]
    )
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
