import { EMPTY_TDS_CREDIT, type DividendIncome, type Employer, type InterestIncome, type TdsCredit } from '../domain/returns/types';
import type { ReturnDraftPatch } from '../domain/returns/draftPatch';
import { normalizeNatureOfEmployment } from './normalizeNatureOfEmployment';

interface PortalDetail { data?: Record<string, unknown>; sr_no?: string | number; }
interface PortalEntry { information_code?: string; information_source?: string; institution_pan?: string; amount?: number; category?: string; section?: string; detail_header?: string[]; details?: PortalDetail[]; }
export interface AisImportData { income_heads?: Record<string, { entries?: PortalEntry[] }>; summary?: { total_tds?: number }; }

function hashId(prefix: string, ...values: unknown[]): string { const text = values.map(String).join('|'); let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return `${prefix}-${(hash >>> 0).toString(36)}`; }
function source(entry: PortalEntry): { name: string; tan: string } { const raw = entry.information_source || ''; const match = raw.match(/^(.+?)\s*\(([^)]+)\)\s*$/); return { name: match?.[1]?.trim() || raw, tan: match?.[2]?.split('.')[0]?.trim() || '' }; }
function numberValue(value: unknown): number { return Number.parseFloat(String(value ?? '0').replace(/,/g, '')) || 0; }
function activeSum(entry: PortalEntry, column: string): number { const header = entry.detail_header || []; const index = header.findIndex((item) => item.toUpperCase().includes(column)); if (index < 0) return 0; const statusIndex = header.length - 1; return (entry.details || []).reduce((sum, detail) => String(detail.data?.[`col_${statusIndex}`] || '').toUpperCase() === 'ACTIVE' ? sum + numberValue(detail.data?.[`col_${index}`]) : sum, 0); }

function employer(entry: PortalEntry): Employer { const origin = source(entry); const basic = activeSum(entry, '17(1)') || entry.amount || 0; return { id: `employer-${(origin.tan || origin.name || 'unknown').trim().toUpperCase()}`, customEmployerName: origin.name, employerName: origin.name || 'Employer from AIS', employerTAN: origin.tan, natureOfEmployment: normalizeNatureOfEmployment('OTH'), employerAddress: '', employerCity: '', employerStateCode: '', employerPinCode: '', employerZipCode: '', salaryNatureRows: [], perquisiteNatureRows: [], section10ExemptionRows: [], basic, da: 0, commission: 0, hra: 0, bonus: 0, allowances: 0, lta: 0, otherAllowance: 0, arrearSalary: 0, perquisites: activeSum(entry, 'VALUE OF PERQUISITES'), profitsInLieu: activeSum(entry, 'PROFITS IN LIEU'), rentPaid: 0, city: '', isMetroCity: false, isGovernmentEmployee: false, isDisabledEmployee: false, commutedPension: 0, gratuity: 0, leaveEncashment: 0, averageMonthlySalary: 0, yearsOfService: 0, unavailedLeaveDays: 0, actualLtaFare: 0, isDomesticTravel: true, journeysInBlock: 0, ltaExempt: 0, numberOfChildren: 0, gratuityAlsoReceived: false, transportAllowance: 0, childrenEducationAllowance: 0, hostelExpenditureAllowance: 0, uniformAllowance: 0, entertainmentAllowance: 0, professionalTax: 0, vrsCompensation: 0, retrenchmentCompensation: 0, otherExempt: 0, tdsDeducted: 0, employerNPS: 0 }; }
function interest(entry: PortalEntry, kind: InterestIncome['kind']): InterestIncome { const origin = source(entry); return { id: hashId('ais-interest', entry.information_code, origin.tan, entry.amount), kind, grossAmount: entry.amount || activeSum(entry, 'AMOUNT PAID'), tdsDeducted: activeSum(entry, 'TDS DEDUCTED'), bankName: origin.name, accountType: kind === 'SAVINGS_BANK' ? 'SAVINGS' : 'FD', accountNumber: '', ifscCode: '', postOfficeName: '', accountNumberPO: '', nscCertificateNumber: '', yearOfPurchase: 0, scssAccountNumber: '', dateOfOpening: '', deductorName: origin.name, deductorTAN: origin.tan, remarks: '' }; }

/** Maps raw AIS import data into canonical draft fields. */
export function mapAisToDraftPatch(data: AisImportData | null | undefined): ReturnDraftPatch {
  if (!data) return {};
  const entries = Object.values(data.income_heads || {}).flatMap((head) => head.entries || []);
  const employers = entries.filter((entry) => entry.section === 'B7' && entry.information_code?.toUpperCase() === 'TDS-ANN.II-SAL').map(employer);
  const sftInterest = entries.filter((entry) => entry.section === 'B2' && entry.information_code?.toUpperCase().startsWith('SFT-016')).map((entry) => interest(entry, entry.information_code?.toUpperCase().includes('(SB)') || entry.category?.toLowerCase().includes('savings') ? 'SAVINGS_BANK' : 'TERM_DEPOSIT'));
  const names = new Set(sftInterest.map((item) => item.deductorName.toLowerCase()));
  const b1Interest = entries.filter((entry) => entry.section === 'B1' && ['TDS-194A', 'TDS-193'].includes(entry.information_code?.toUpperCase() || '')).map((entry) => interest(entry, entry.information_code?.toUpperCase() === 'TDS-193' ? 'SAVINGS_BANK' : 'TERM_DEPOSIT')).filter((item) => !names.has(item.deductorName.toLowerCase()));
  const dividends: DividendIncome[] = entries.filter((entry) => entry.section === 'B2' && ['SFT-015', 'SFT-018(DIV)'].includes(entry.information_code?.toUpperCase() || '')).map((entry) => { const origin = source(entry); return { id: hashId('ais-dividend', origin.tan, entry.amount), section: entry.information_code?.includes('018') ? '194' : '194', grossAmount: entry.amount || 0, tdsDeducted: 0, companyName: origin.name, companyPAN: entry.institution_pan || '', deductorTAN: origin.tan, isin: '', category: entry.information_code?.includes('018') ? 'MUTUAL_FUND' : 'EQUITY', q1: 0, q2: 0, q3: 0, q4: 0, q5: 0 }; });
  const taxes: TdsCredit[] = entries.filter((entry) => entry.section === 'B1' && entry.information_code?.toUpperCase().startsWith('TDS-')).map((entry) => { const origin = source(entry); const section = entry.information_code!.toUpperCase().replace('TDS-', ''); const tax = activeSum(entry, 'TDS DEDUCTED'); return { ...structuredClone(EMPTY_TDS_CREDIT), id: hashId('ais-tds', origin.tan, section, entry.amount), section, deductorName: origin.name, deductorTAN: origin.tan, deductorPAN: entry.institution_pan || '', grossAmount: activeSum(entry, 'AMOUNT PAID') || entry.amount || 0, taxDeducted: tax, verified26AS: true, schedule: section === '192' ? 'TDS1' : 'TDS2', headOfIncome: section === '192' ? 'NA' : 'OS', claimOutOfTotTDSOnAmtPaid: tax }; });
  return { employers, otherSources: { interest: [...sftInterest, ...b1Interest], dividends }, taxes: { tds: taxes }, provenance: [{ source: 'AIS', importedAt: new Date().toISOString(), reference: 'direct-import' }] };
}
