import { createEmptyFinancialParticulars, createEmptyReturnDraft } from './factory';
import type { BankAccount, Category80D, DeductionLoan, DividendIncome, Donation80G, Employer, ExemptIncomeEntry, FinancialParticulars, GiftIncome, HomeLoan, HouseProperty, InterestIncome, Investment80C, Policy80D, PresumptiveBusiness, ReturnDraft, Section89AEntry, TaxChallan, TcsCredit, TdsCredit, WinningIncome, OtherIncomeEntry, DtaaIncomeEntry, AccumulatedPfEntry, UnexplainedIncomeDetails, OtherSourcesDeductions, SpecialRateIncomeEntry } from './types';

type JsonRecord = Record<string, unknown>;
const isRecord = (value: unknown): value is JsonRecord => value !== null && typeof value === 'object' && !Array.isArray(value);
const text = (value: unknown, fallback = ''): string => typeof value === 'string' ? value : value == null ? fallback : String(value);
const bool = (value: unknown, fallback = false): boolean => typeof value === 'boolean' ? value : fallback;
const money = (value: unknown): number => { const parsed = typeof value === 'number' ? value : typeof value === 'string' && value.trim() ? Number(value) : 0; return Number.isFinite(parsed) && parsed >= 0 ? parsed : 0; };
const signed = (value: unknown): number => { const parsed = typeof value === 'number' ? value : typeof value === 'string' && value.trim() ? Number(value) : 0; return Number.isFinite(parsed) ? parsed : 0; };
const integer = (value: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): number => Math.min(max, Math.max(min, Math.trunc(money(value))));
const records = (value: unknown): JsonRecord[] => Array.isArray(value) ? value.filter(isRecord) : [];
const array = (source: JsonRecord, key: string): JsonRecord[] | undefined => Array.isArray(source[key]) ? records(source[key]) : undefined;
function stableStringify(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`; if (isRecord(value)) return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`; return JSON.stringify(value) ?? 'null'; }
function itemId(prefix: string, index: number, item: JsonRecord): string { if (typeof item.id === 'string' && item.id.trim()) return item.id; const input = `${prefix}|${index}|${stableStringify(item)}`; let hash = 0x811c9dc5; for (let i = 0; i < input.length; i += 1) { hash ^= input.charCodeAt(i); hash = Math.imul(hash, 0x01000193); } return `${prefix}-${(hash >>> 0).toString(36)}`; }
const enumValue = <T extends string>(value: unknown, allowed: readonly T[], fallback: T): T => allowed.includes(text(value) as T) ? text(value) as T : fallback;
const financial = (value: unknown): FinancialParticulars => { const source = isRecord(value) ? value : {}; const result = createEmptyFinancialParticulars(); for (const key of Object.keys(result) as Array<keyof FinancialParticulars>) result[key] = money(source[key]); return result; };
const gstRows = (value: unknown): Array<{ id: string; gstin: string; turnover: number }> => records(value).map((row, index) => ({ id: itemId('gst', index, row), gstin: text(row.gstin), turnover: money(row.turnover) }));
const salaryRows = (value: unknown, prefix: string): Array<{ id: string; natureCode: string; otherDescription: string; amount: number }> => records(value).map((row, index) => ({ id: itemId(prefix, index, row), natureCode: text(row.natureCode), otherDescription: text(row.otherDescription), amount: money(row.amount) }));

function employer(item: JsonRecord, index: number): Employer {
  const m = (key: string, alias?: string): number => money(item[key] ?? (alias ? item[alias] : undefined));
  return { id: itemId('employer', index, item), customEmployerName: text(item.customEmployerName), employerName: text(item.employerName ?? item.customEmployerName), employerTAN: text(item.employerTAN), natureOfEmployment: text(item.natureOfEmployment), employerAddress: text(item.employerAddress), employerCity: text(item.employerCity), employerStateCode: text(item.employerStateCode), employerPinCode: text(item.employerPinCode), employerZipCode: text(item.employerZipCode), salaryNatureRows: salaryRows(item.salaryNatureRows, 'salary-nature'), perquisiteNatureRows: salaryRows(item.perquisiteNatureRows, 'perquisite-nature'), section10ExemptionRows: salaryRows(item.section10ExemptionRows, 'section10-exemption'), basic: m('basic'), da: m('da'), commission: m('commission'), hra: m('hra','hraReceived'), bonus: m('bonus'), allowances: m('allowances'), lta: m('lta'), otherAllowance: m('otherAllowance'), arrearSalary: m('arrearSalary'), perquisites: m('perquisites'), profitsInLieu: m('profitsInLieu'), rentPaid: m('rentPaid'), city: text(item.city), isMetroCity: bool(item.isMetroCity), isGovernmentEmployee: bool(item.isGovernmentEmployee), isDisabledEmployee: bool(item.isDisabledEmployee), commutedPension: m('commutedPension'), gratuity: m('gratuity'), leaveEncashment: m('leaveEncashment'), averageMonthlySalary: m('averageMonthlySalary'), yearsOfService: integer(item.yearsOfService), unavailedLeaveDays: integer(item.unavailedLeaveDays), actualLtaFare: m('actualLtaFare'), isDomesticTravel: bool(item.isDomesticTravel), journeysInBlock: integer(item.journeysInBlock), ltaExempt: m('ltaExempt'), numberOfChildren: integer(item.numberOfChildren), gratuityAlsoReceived: bool(item.gratuityAlsoReceived), transportAllowance: m('transportAllowance'), childrenEducationAllowance: m('childrenEducationAllowance'), hostelExpenditureAllowance: m('hostelExpenditureAllowance'), uniformAllowance: m('uniformAllowance'), entertainmentAllowance: m('entertainmentAllowance'), professionalTax: m('professionalTax','profTax'), vrsCompensation: m('vrsCompensation'), retrenchmentCompensation: m('retrenchmentCompensation'), otherExempt: m('otherExempt'), tdsDeducted: m('tdsDeducted'), employerNPS: m('employerNPS') };
}
function homeLoan(item: JsonRecord): HomeLoan { return { lenderType: enumValue(item.lenderType, ['B','I'] as const, 'B'), lenderName: text(item.lenderName), lenderPAN: text(item.lenderPAN), loanAccountNo: text(item.loanAccountNo), dateOfLoan: text(item.dateOfLoan), totalLoanAmount: money(item.totalLoanAmount), loanOutstandingAmount: money(item.loanOutstandingAmount), interestUs24B: money(item.interestUs24B), constructionCompletionDate: text(item.constructionCompletionDate), completedWithin5Years: bool(item.completedWithin5Years), preConstructionInterest: money(item.preConstructionInterest) }; }
function property(item: JsonRecord, index: number): HouseProperty {
  const raw = text(item.propertyType ?? item.hpType).toUpperCase(); const propertyType = raw === 'LET_OUT' || raw === 'LET' ? 'LET_OUT' : raw === 'DEEMED_LET_OUT' ? 'DEEMED_LET_OUT' : 'SELF_OCCUPIED';
  const tenantRows = records(item.tenantDetails); const legacyTenant = text(item.tenantName) || text(item.tenantPAN) || text(item.tenantAadhaar) ? [{ tenantSNo: 1, name: text(item.tenantName), pan: text(item.tenantPAN), aadhaar: text(item.tenantAadhaar), panOrTan: text(item.tenantPAN) }] : [];
  const tenantDetails = (tenantRows.length ? tenantRows : legacyTenant).map((tenant, tenantIndex) => ({ tenantSNo: integer(tenant.tenantSNo) || tenantIndex + 1, name: text(tenant.name), pan: text(tenant.pan), aadhaar: text(tenant.aadhaar), panOrTan: text(tenant.panOrTan ?? tenant.pan) }));
  return { id: itemId('property', index, item), name: text(item.name, `Property ${index + 1}`), propertySequenceNo: integer(item.propertySequenceNo, 1) || index + 1, propertyType, address: text(item.address), premisesName: text(item.premisesName), roadOrStreet: text(item.roadOrStreet), area: text(item.area), city: text(item.city), state: text(item.state), pinCode: text(item.pinCode ?? item.pincode), zipCode: text(item.zipCode), countryCode: text(item.countryCode, '91'), propertyIdentificationNo: text(item.propertyIdentificationNo), propertyOwnerType: enumValue(item.propertyOwnerType, ['SE','MI','SP','OT'] as const, 'SE'), propertyOwnerOther: text(item.propertyOwnerOther), ownershipType: bool(item.isCoOwned) ? 'JOINT' : 'SOLE', ownershipShare: money(item.ownershipShare), isCoOwned: bool(item.isCoOwned), isPropertyInJointOwnership: bool(item.isCoOwned), coOwners: records(item.coOwners).map((owner, ownerIndex) => ({ coOwnerSNo: ownerIndex + 1, name: text(owner.name), pan: text(owner.pan), aadhaar: text(owner.aadhaar), share: money(owner.share) })), annualRent: money(item.annualRent ?? item.grossRent), municipalRateableValue: money(item.municipalRateableValue), fairRentValue: money(item.fairRentValue), standardRent: money(item.standardRent), annualLettingValue: money(item.annualLettingValue), unrealizedRent: money(item.unrealizedRent), arrearsOfRent: money(item.arrearsOfRent), vacancyPeriodMonths: integer(item.vacancyPeriodMonths, 0, 12), municipalTaxesPaid: money(item.municipalTaxesPaid ?? item.munTax), interestOnLoan: money(item.interestOnLoan ?? item.homeLoanInt ?? item.sopLoanInt), preConstructionInterest: money(item.preConstructionInterest), lenderName: text(item.lenderName), lenderPAN: text(item.lenderPAN), lenderType: enumValue(item.lenderType, ['B','I'] as const, 'B'), loanAccountNo: text(item.loanAccountNo), loanSanctionDate: text(item.loanSanctionDate), constructionCompletionDate: text(item.constructionCompletionDate), principalRepayment: money(item.principalRepayment), totalLoanAmount: money(item.totalLoanAmount), loanOutstandingAmount: money(item.loanOutstandingAmount), completedWithin5Years: bool(item.completedWithin5Years), homeLoans: records(item.homeLoans).map(homeLoan), tenantDetails, tenantName: tenantDetails[0]?.name ?? text(item.tenantName), tenantPAN: tenantDetails[0]?.pan ?? text(item.tenantPAN), tenantAadhaar: tenantDetails[0]?.aadhaar ?? text(item.tenantAadhaar), passThroughIncome: money(item.passThroughIncome), grossAnnualValue: money(item.grossAnnualValue), netAnnualValue: money(item.netAnnualValue), standardDeduction30Pct: money(item.standardDeduction30Pct), incomeFromHP: signed(item.incomeFromHP), maxRent: money(item.maxRent), preConstructionInterestClaimed: money(item.preConstructionInterestClaimed) };
}
function business(item: JsonRecord, index: number): PresumptiveBusiness {
  const scheme = enumValue(item.scheme ?? item.bizPresumptive, ['44AD','44ADA','44AE'] as const, '44AD'); const common = { id: itemId('business', index, item), businessName: text(item.businessName), natureCode: text(item.natureCode ?? item.nicCode), description: text(item.description ?? item.businessNature), declaredIncome: money(item.declaredIncome ?? item.bizDeclared), gstinTurnovers: gstRows(item.gstinTurnovers ?? item.gstinTurnoverRows), financialParticulars: financial(item.financialParticulars ?? item.scheduleBP) };
  if (scheme === '44ADA') return { ...common, scheme, grossReceipts: money(item.grossReceipts ?? item.bizTurnover), digitalReceipts: money(item.digitalReceipts), nonDigitalReceipts: money(item.nonDigitalReceipts) };
  if (scheme === '44AE') return { ...common, scheme, vehicles: records(item.vehicles).map((vehicle, vehicleIndex) => ({ id: itemId('vehicle', vehicleIndex, vehicle), vehicleNumber: text(vehicle.vehicleNumber), vehicleType: enumValue(vehicle.vehicleType, ['HEAVY','OTHER'] as const, 'OTHER'), tonnage: money(vehicle.tonnage), ownedMonths: integer(vehicle.ownedMonths, 0, 12), leasedOrHired: bool(vehicle.leasedOrHired), presumptiveIncome: money(vehicle.presumptiveIncome) })) };
  const digital = money(item.digitalReceipts ?? item.digitalTurnover); const nonDigital = money(item.nonDigitalReceipts ?? (item.grossTurnover !== undefined ? Math.max(0, money(item.grossTurnover) - digital) : item.bizTurnover));
  return { ...common, scheme, digitalReceipts: digital, nonDigitalReceipts: nonDigital, digitalPresumptiveIncome: money(item.digitalPresumptiveIncome), nonDigitalPresumptiveIncome: money(item.nonDigitalPresumptiveIncome) };
}
function interest(item: JsonRecord, index: number): InterestIncome { return { id: itemId('interest', index, item), kind: enumValue(item.kind ?? item.itdTag, ['SAVINGS_BANK','TERM_DEPOSIT','IT_REFUND','POST_OFFICE','NSC','SCSS','OTHER','BONDS','SECURITIES','PF_10_11_FIRST','PF_10_11_SECOND','PF_10_12_FIRST','PF_10_12_SECOND'] as const, 'OTHER'), grossAmount: money(item.grossAmount ?? item.amount ?? item.interestEarned), tdsDeducted: money(item.tdsDeducted), bankName: text(item.bankName ?? item.payerName), accountType: enumValue(item.accountType, ['SAVINGS','CURRENT','FD',''] as const, ''), accountNumber: text(item.accountNumber), ifscCode: text(item.ifscCode), postOfficeName: text(item.postOfficeName), accountNumberPO: text(item.accountNumberPO), nscCertificateNumber: text(item.nscCertificateNumber), yearOfPurchase: integer(item.yearOfPurchase), scssAccountNumber: text(item.scssAccountNumber), dateOfOpening: text(item.dateOfOpening), deductorName: text(item.deductorName), deductorTAN: text(item.deductorTAN), remarks: text(item.remarks) }; }
const scalarInterest = (source: JsonRecord): JsonRecord[] => [['SAVINGS_BANK','interestSB'],['TERM_DEPOSIT','interestFD'],['TERM_DEPOSIT','interestRD'],['NSC','nscInterest'],['SCSS','scssInterest'],['POST_OFFICE','postOfficeInterest'],['IT_REFUND','incomeFromITRefund'],['PF_10_11_FIRST','pfInterest10_11_first'],['PF_10_11_SECOND','pfInterest10_11_second'],['PF_10_12_FIRST','pfInterest10_12_first'],['PF_10_12_SECOND','pfInterest10_12_second'],['OTHER','otherInterest']].flatMap(([kind,key]) => money(source[key]) > 0 ? [{ kind, grossAmount: source[key] }] : []);
function policy(item: JsonRecord, index: number): Policy80D { return { id: itemId('80d', index, item), insurerName: text(item.insurerName), policyNo: text(item.policyNo), premiumAmount: money(item.premiumAmount), policyType: enumValue(item.policyType, ['INDIVIDUAL','FAMILY_FLOATER','GROUP','OTHER'] as const, 'INDIVIDUAL'), dateOfCommencement: text(item.dateOfCommencement) }; }
function category(value: unknown): Category80D { const item = isRecord(value) ? value : {}; return { policies: records(item.policies).map(policy), preventiveCheckup: money(item.preventiveCheckup), medicalExpense: money(item.medicalExpense) }; }

const exemptScalarMap: Array<[ExemptIncomeEntry['kind'], string, string?]> = [['AGRICULTURE','agricultureIncome','agricultureExpenses'],['PPF_INTEREST','ppfInterest'],['SUKANYA_INTEREST','sukanyaSamriddhiInterest'],['OTHER_INTEREST','otherExemptInterest'],['LTCG_10_33','ltcgExempt'],['LTCG_10_38','ltcgExempt38'],['GRATUITY','gratuityExempt'],['LEAVE_ENCASHMENT','leaveEncashmentExempt'],['VRS','vrsCompensationExempt'],['COMMUTED_PENSION','commutationPension'],['FIRM_PROFIT_SHARE','shareOfProfitFirm'],['OTHER','otherExemptIncome']];
const known = new Set(['assessmentYear','year','ay','form','itrForm','itrType','regime','taxRegime','name','pan','email','mobile','dob','dateOfBirth','filing','filingSection','returnType','originalAcknowledgementNumber','originalFilingDate','noticeNumber','employerEntries','housePropertyEntries','businessEntries','businesses','interestEntries','bankInterestEntries','dividendEntries','familyPensionEntry','familyPension','winningsEntries','giftEntries','section80C','section80D','donationEntries','deductionLoans','tdsEntries','tcsEntries','advanceTaxEntries','selfAssessmentTaxEntries','bankAccountData','bankAccountDetails','verification','provenance','importProvenance','exemptIncomeEntries','housePropertyPassThroughIncome','passThroughIncome','capitalGainsSchedule','capitalGainTransactions','basic','da','hra','hraReceived','bonus','allowances','perquisites','profitsInLieu','profTax','tdsS192','grossRent','munTax','homeLoanInt','sopLoanInt','bizPresumptive','bizTurnover','bizDeclared','interestSB','interestFD','interestRD','nscInterest','scssInterest','postOfficeInterest','incomeFromITRefund','otherInterest','dividends','dividendShares','dividendMF','dividendUnits','lotteryIncome','crosswordPuzzleIncome','horseRaceIncome','cardGameIncome','giftsFromRelatives','giftsFromNonRelatives','s80C_epf','s80C_ppf','s80C_elss','s80C_lic','s80C_home','s80G','tds194A','tdsOther','adv15Jun','adv15Sep','adv15Dec','adv15Mar','selfTax','osOtherIncomeEntries','osDtaaEntries','osDtaaAggregates','osSection89AEntries','osSection89AAggregates','osAccumulatedPfEntries','osAccumulatedPfAggregates','osSpecialRateIncomeEntries','osUnexplainedIncome','osDeductions','pfInterest10_11_first','pfInterest10_11_second','pfInterest10_12_first','pfInterest10_12_second','onlineGamingIncome','raceHorseActivityIncome','unexplainedIncome115BBE',...exemptScalarMap.flatMap(([,amount,expenses]) => expenses ? [amount,expenses] : [amount])]);

/** Defensively converts the current flat saved payload into the normalized domain. */
export function adaptLegacyReturn(payload: unknown): ReturnDraft {
  const source = isRecord(payload) ? payload : {}; const rawForm = text(source.form ?? source.itrForm ?? source.itrType).replace(/^ITR([1-4])$/, 'ITR-$1'); const rawRegime = text(source.regime ?? source.taxRegime).toLowerCase();
  const normalizedForm = enumValue(rawForm, ['ITR-1','ITR-2','ITR-3','ITR-4'] as const, 'ITR-1');
  const draft = createEmptyReturnDraft(text(source.assessmentYear ?? source.year ?? source.ay), normalizedForm, rawRegime === 'old' ? 'old' : 'new');
  draft.personal = { name: text(source.name), pan: text(source.pan), email: text(source.email), mobile: text(source.mobile), dateOfBirth: text(source.dateOfBirth ?? source.dob) || null };
  const filing = isRecord(source.filing) ? source.filing : source; draft.filing = { filingSection: enumValue(filing.filingSection, ['139(1)','139(4)','139(5)','119(2)(b)'] as const, '139(1)'), returnType: enumValue(filing.returnType, ['ORIGINAL','REVISED'] as const, text(filing.filingSection) === '139(5)' ? 'REVISED' : 'ORIGINAL'), originalAcknowledgementNumber: text(filing.originalAcknowledgementNumber), originalFilingDate: text(filing.originalFilingDate) || null, noticeNumber: text(filing.noticeNumber) };
  draft.employers = (array(source,'employerEntries') ?? (['basic','da','hra','bonus'].some((key) => money(source[key]) > 0) ? [source] : [])).map(employer);
  draft.houseProperties = (array(source,'housePropertyEntries') ?? (['grossRent','munTax','homeLoanInt','sopLoanInt'].some((key) => money(source[key]) > 0) ? [source] : [])).slice(0, draft.form === 'ITR-1' || draft.form === 'ITR-4' ? 2 : undefined).map(property);
  draft.housePropertyPassThroughIncome = signed(source.housePropertyPassThroughIncome ?? source.passThroughIncome ?? draft.houseProperties[0]?.passThroughIncome);
  draft.capitalGainsSchedule = isRecord(source.capitalGainsSchedule) ? source.capitalGainsSchedule : {};
  draft.businesses = (array(source,'businessEntries') ?? array(source,'businesses') ?? (['bizTurnover','bizDeclared'].some((key) => money(source[key]) > 0) ? [source] : [])).map(business);
  draft.otherSources.interest = (array(source,'interestEntries') ?? array(source,'bankInterestEntries') ?? scalarInterest(source)).map(interest);
  const dividendItems: JsonRecord[] = array(source,'dividendEntries') ?? (money(source.dividends ?? source.dividendShares) + money(source.dividendMF) + money(source.dividendUnits) > 0 ? [{ grossAmount: money(source.dividends ?? source.dividendShares) + money(source.dividendMF) + money(source.dividendUnits) }] : []);
  draft.otherSources.dividends = dividendItems.map((item,index): DividendIncome => ({ id: itemId('dividend',index,item), section: enumValue(item.section, ['194','10(22e)','10(22f)','115BBDA','115BBDAaiii','115A1ai','115A1aA','115AC','115ACA','115AD1i','DTAA'] as const, '194'), grossAmount: money(item.grossAmount ?? item.dividendAmount), tdsDeducted: money(item.tdsDeducted), companyName: text(item.companyName), companyPAN: text(item.companyPAN), deductorTAN: text(item.deductorTAN), isin: text(item.isin), category: enumValue(item.category,['EQUITY','PREFERENCE','MUTUAL_FUND',''] as const,''), q1: money(item.q1), q2: money(item.q2), q3: money(item.q3), q4: money(item.q4), q5: money(item.q5) }));
  const pension = isRecord(source.familyPensionEntry) ? source.familyPensionEntry : {}; draft.otherSources.familyPension = { grossAmount: money(pension.grossAmount ?? source.familyPension), payerName: text(pension.payerName), relationToPensioner: text(pension.relationToPensioner) };
  const wins: JsonRecord[] = array(source,'winningsEntries') ?? [['LOTTERY','lotteryIncome'],['CARD_GAME','crosswordPuzzleIncome'],['HORSE_RACE','horseRaceIncome'],['CARD_GAME','cardGameIncome'],['ONLINE_GAMING','onlineGamingIncome'],['RACE_HORSE_ACTIVITY','raceHorseActivityIncome']].flatMap(([type,key]) => money(source[key]) > 0 ? [{type,grossAmount:source[key]}] : []); draft.otherSources.winnings = wins.map((item,index): WinningIncome => ({ id:itemId('winning',index,item), type:enumValue(item.type,['LOTTERY','BETTING','CARD_GAME','HORSE_RACE','ONLINE_GAMING','RACE_HORSE_ACTIVITY','UNEXPLAINED_115BBE'] as const,'LOTTERY'), grossAmount:money(item.grossAmount), tdsDeducted:money(item.tdsDeducted), payerName:text(item.payerName), payerTAN:text(item.payerTAN), dateOfWinning:text(item.dateOfWinning), q1:money(item.q1), q2:money(item.q2), q3:money(item.q3), q4:money(item.q4), q5:money(item.q5), receipts:money(item.receipts), deductionUs57:money(item.deductionUs57), amountNotDeductibleUs58:money(item.amountNotDeductibleUs58), profitChargeableUs59:money(item.profitChargeableUs59), balance:money(item.balance) }));
  const gifts: JsonRecord[] = array(source,'giftEntries') ?? [['CASH','giftsFromNonRelatives',false],['CASH','giftsFromRelatives',true]].flatMap(([propertyType,key,fromRelative]) => money(source[String(key)]) > 0 ? [{propertyType,value:source[String(key)],fromRelative}] : []); draft.otherSources.gifts = gifts.map((item,index): GiftIncome => ({ id:itemId('gift',index,item), propertyType:enumValue(item.propertyType,['IMMOVABLE','CASH','MOVABLE','OTHER'] as const,'OTHER'), value:money(item.value), donorName:text(item.donorName), donorRelation:text(item.donorRelation), dateOfReceipt:text(item.dateOfReceipt), description:text(item.description), fromRelative:bool(item.fromRelative), receivedOnMarriage:bool(item.receivedOnMarriage), considerationKind:enumValue(item.considerationKind,['WITHOUT_CONSIDERATION','INADEQUATE_CONSIDERATION'] as const,'WITHOUT_CONSIDERATION'), stampDutyValue:money(item.stampDutyValue), considerationPaid:money(item.considerationPaid), fairMarketValue:money(item.fairMarketValue) }));
  draft.otherSources.otherIncome = records(source.osOtherIncomeEntries).map((item, index): OtherIncomeEntry => ({ id: itemId('osOther', index, item), nature: text(item.nature), description: text(item.description), amount: money(item.amount) }));
  draft.otherSources.dtaaIncome = records(source.osDtaaEntries).map((item, index): DtaaIncomeEntry => ({ id: itemId('osDtaa', index, item), amount: money(item.amount), natureOfIncome: enumValue(item.natureOfIncome, ['1ai','1aiii','1b','1c','1d','2ai','2aii','2d','2e'] as const, '1ai'), countryName: text(item.countryName), countryCode: text(item.countryCode), dtaaArticle: text(item.dtaaArticle), rateAsPerTreaty: money(item.rateAsPerTreaty), rateAsPerITAct: money(item.rateAsPerITAct), taxResidencyCertificate: enumValue(item.taxResidencyCertificate, ['Y','N'] as const, 'N'), itemNoIncl: text(item.itemNoIncl), applicableRate: money(item.applicableRate), q1: money(item.q1), q2: money(item.q2), q3: money(item.q3), q4: money(item.q4), q5: money(item.q5) }));
  const dtaaAggSource = isRecord(source.osDtaaAggregates) ? source.osDtaaAggregates : {}; draft.otherSources.dtaaAggregates = { totalAmountTaxUsDtaa: money(dtaaAggSource.totalAmountTaxUsDtaa) };
  draft.otherSources.section89A = records(source.osSection89AEntries).map((item, index): Section89AEntry => ({ id: itemId('os89a', index, item), countryCode: enumValue(item.countryCode, ['US','UK','CA'] as const, 'US'), amount: money(item.amount) }));
  const agg89aSource = isRecord(source.osSection89AAggregates) ? source.osSection89AAggregates : {}; draft.otherSources.section89AAggregates = { incomeNotified89AOS: money(agg89aSource.incomeNotified89AOS), incomeNotifiedOther89AOS: money(agg89aSource.incomeNotifiedOther89AOS), incomeNotifiedPriorYear89AOS: money(agg89aSource.incomeNotifiedPriorYear89AOS), incomeReliefUs89AOS: money(agg89aSource.incomeReliefUs89AOS) };
  draft.otherSources.accumulatedPf = records(source.osAccumulatedPfEntries).map((item, index): AccumulatedPfEntry => ({ id: itemId('osPf', index, item), assessmentYear: enumValue(item.assessmentYear, ['2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21','2021-22','2022-23','2023-24','2024-25','2025-26'] as const, '2025-26'), incomeBenefit: money(item.incomeBenefit), taxBenefit: money(item.taxBenefit) }));
  const pfAggSource = isRecord(source.osAccumulatedPfAggregates) ? source.osAccumulatedPfAggregates : {}; draft.otherSources.accumulatedPfAggregates = { totalIncomeBenefit: money(pfAggSource.totalIncomeBenefit), totalTaxBenefit: money(pfAggSource.totalTaxBenefit) };
  draft.otherSources.specialRateIncome = records(source.osSpecialRateIncomeEntries).map((item, index): SpecialRateIncomeEntry => ({ id: itemId('osSpecRate', index, item), sourceDescription: enumValue(item.sourceDescription, ['5A1ai','5A1aA','5A1aii','5A1aiia','5A1aiiaa','5A1aiiab','5A1aiiac','5A1aiii','5A1bA','5AC1ab','5AC1abD','5ACA1a','5AD1i','5AD1iP','5BBA','5BBF','5BBG','5Ea','5A1aiiaaP','5A1aiiaa2P','5AD1iDiv'] as const, '5A1ai'), sourceAmount: money(item.sourceAmount) }));
  const unexpSource = isRecord(source.osUnexplainedIncome) ? source.osUnexplainedIncome : {};
  draft.otherSources.unexplainedIncome = { cashCreditsUs68: money(unexpSource.cashCreditsUs68), unexplainedInvestmentsUs69: money(unexpSource.unexplainedInvestmentsUs69), unexplainedMoneyUs69A: money(unexpSource.unexplainedMoneyUs69A), undisclosedInvestmentsUs69B: money(unexpSource.undisclosedInvestmentsUs69B), unexplainedExpenditureUs69C: money(unexpSource.unexplainedExpenditureUs69C), hundiBorrowingUs69D: money(unexpSource.hundiBorrowingUs69D), priorYearBusinessTrust562xii: money(unexpSource.priorYearBusinessTrust562xii), priorYearLifeInsurance562xiii: money(unexpSource.priorYearLifeInsurance562xiii) } as UnexplainedIncomeDetails;
  const dedSource = isRecord(source.osDeductions) ? source.osDeductions : {};
  draft.otherSources.deductions = { expenses: money(dedSource.expenses), interestExpenseUs57: money(dedSource.interestExpenseUs57), interestExpenseEligibleUs57: money(dedSource.interestExpenseEligibleUs57), familyPensionDeductionUs57iia: money(dedSource.familyPensionDeductionUs57iia), depreciation: money(dedSource.depreciation), totalDeductions: money(dedSource.totalDeductions), amountNotDeductibleUs58: money(dedSource.amountNotDeductibleUs58), profitChargeableUs59: money(dedSource.profitChargeableUs59) } as OtherSourcesDeductions;
  const exempt = array(source,'exemptIncomeEntries'); const exemptItems: JsonRecord[] = exempt ?? exemptScalarMap.flatMap(([kind,amountKey,expenseKey]) => money(source[amountKey]) > 0 || (expenseKey && money(source[expenseKey]) > 0) ? [{kind,grossAmount:source[amountKey],expenses:expenseKey ? source[expenseKey] : 0}] : []); draft.exemptIncome = exemptItems.map((item,index): ExemptIncomeEntry => ({ id:itemId('exempt',index,item), kind:enumValue(item.kind,['AGRICULTURE','PPF_INTEREST','SUKANYA_INTEREST','OTHER_INTEREST','LTCG_10_33','LTCG_10_38','GRATUITY','LEAVE_ENCASHMENT','VRS','COMMUTED_PENSION','FIRM_PROFIT_SHARE','OTHER'] as const,'OTHER'), description:text(item.description), grossAmount:money(item.grossAmount), expenses:money(item.expenses) }));
  const s80c = isRecord(source.section80C) ? source.section80C : {}; const investments: JsonRecord[] = Array.isArray(s80c.investments) ? records(s80c.investments) : [['EPF','s80C_epf'],['PPF','s80C_ppf'],['ELSS','s80C_elss'],['LIC','s80C_lic'],['HomeLoan','s80C_home']].flatMap(([investmentType,key]) => money(source[key]) > 0 ? [{investmentType,amount:source[key]}] : []); draft.deductions.section80C = investments.map((item,index): Investment80C => ({ id:itemId('80c',index,item), investmentType:text(item.investmentType,'OTHER'), identificationNo:text(item.identificationNo), accountOrPolicyNo:text(item.accountOrPolicyNo), amount:money(item.amount), dateOfInvestment:text(item.dateOfInvestment), institutionName:text(item.institutionName), institutionPAN:text(item.institutionPAN) }));
  const s80d = isRecord(source.section80D) ? source.section80D : {}; draft.deductions.section80D = { selfSeniorCitizen:enumValue(s80d.selfSeniorCitizen,['Y','N','S'] as const,'N'), parentsSeniorCitizen:enumValue(s80d.parentsSeniorCitizen,['Y','N','P'] as const,'N'), selfFamily:category(s80d.selfFamily), selfFamilySenior:category(s80d.selfFamilySenior), parents:category(s80d.parents), parentsSenior:category(s80d.parentsSenior) };
  const donations: JsonRecord[] = array(source,'donationEntries') ?? (money(source.s80G)>0 ? [{donationAmtOtherMode:source.s80G}] : []); draft.deductions.section80G = donations.map((item,index): Donation80G => ({ id:itemId('80g',index,item), category:enumValue(item.category,['100_NO_APPROVAL','50_NO_APPROVAL','100_APPROVAL_REQD','50_APPROVAL_REQD'] as const,'50_APPROVAL_REQD'), doneeName:text(item.doneeName), doneePAN:text(item.doneePAN), arnNumber:text(item.arnNumber), addrDetail:text(item.addrDetail), city:text(item.city), stateCode:text(item.stateCode), pinCode:text(item.pinCode), donationAmtCash:money(item.donationAmtCash), donationAmtOtherMode:money(item.donationAmtOtherMode ?? item.amount), transactionRefNum:text(item.transactionRefNum), ifscCode:text(item.ifscCode), donationDate:text(item.donationDate), receiptNumber:text(item.receiptNumber), notes:text(item.notes) }));
  const loanRoot = isRecord(source.deductionLoans) ? source.deductionLoans : {}; const loanItems: JsonRecord[] = ['80E','80EE','80EEA','80EEB'].flatMap((section) => { const group=isRecord(loanRoot[`section${section}`]) ? loanRoot[`section${section}`] as JsonRecord : {}; return records(group.loans).map((loan): JsonRecord=>({...loan,section})); }); draft.deductions.loans = { section80EEAStampDutyValue: money(isRecord(loanRoot.section80EEA) ? loanRoot.section80EEA.stampDutyValue : 0), loans:loanItems.map((item,index): DeductionLoan => ({ id:itemId('loan',index,item), section:enumValue(item.section,['80E','80EE','80EEA','80EEB'] as const,'80E'), loanTakenFrom:enumValue(item.loanTakenFrom,['B','I'] as const,'B'), lenderName:text(item.lenderName ?? item.bankOrInstnName), lenderPAN:text(item.lenderPAN), loanAccountNo:text(item.loanAccountNo ?? item.loanAccNo), dateOfLoan:text(item.dateOfLoan), totalLoanAmount:money(item.totalLoanAmount ?? item.totalLoanAmt), outstandingAmount:money(item.outstandingAmount ?? item.loanOutstandingAmt), interestAmount:money(item.interestAmount), firstTimeBuyerEligible:bool(item.firstTimeBuyerEligible), vehicleRegNo:text(item.vehicleRegNo) })) };
  const tds: JsonRecord[] = array(source,'tdsEntries') ?? [['192','tdsS192'],['194A','tds194A'],['OTHER','tdsOther']].flatMap(([section,key])=>money(source[key])>0?[{section,tdsDeducted:source[key]}]:[]); draft.taxes.tds=tds.map((item,index):TdsCredit=>({id:itemId('tds',index,item),section:text(item.section),deductorName:text(item.deductorName),deductorTAN:text(item.deductorTAN),deductorPAN:text(item.deductorPAN),certificateNo:text(item.certificateNo),grossAmount:money(item.grossAmount??item.incomeAmount),taxDeducted:money(item.taxDeducted??item.tdsDeducted),deductionDate:text(item.deductionDate),uniqueTransactionNo:text(item.uniqueTransactionNo),financialYear:text(item.financialYear),verified26AS:bool(item.verified26AS),claimedInReturn:item.claimedInReturn!==false})); draft.taxes.tcs=(array(source,'tcsEntries')??[]).map((item,index):TcsCredit=>({id:itemId('tcs',index,item),collectorName:text(item.collectorName),collectorTAN:text(item.collectorTAN),grossAmount:money(item.grossAmount),taxCollected:money(item.taxCollected??item.tcsCollected),claimedInReturn:item.claimedInReturn!==false}));
  const advance: JsonRecord[]=array(source,'advanceTaxEntries')??[['15JUN','adv15Jun'],['15SEP','adv15Sep'],['15DEC','adv15Dec'],['15MAR','adv15Mar']].flatMap(([depositDate,key])=>money(source[key])>0?[{depositDate,amount:source[key]}]:[]); const sat: JsonRecord[]=array(source,'selfAssessmentTaxEntries')??(money(source.selfTax)>0?[{amount:source.selfTax}]:[]); const challanItems: JsonRecord[]=[...advance.map((x):JsonRecord=>({...x,kind:'ADVANCE_TAX'})),...sat.map((x):JsonRecord=>({...x,kind:'SELF_ASSESSMENT'}))]; draft.taxes.challans=challanItems.map((item,index):TaxChallan=>({id:itemId('challan',index,item),kind:item.kind as TaxChallan['kind'],bsrCode:text(item.bsrCode),depositDate:text(item.depositDate),challanSerialNo:text(item.challanSerialNo??item.challanNo),amount:money(item.amount),cin:text(item.cin)}));
  const bankRoot=isRecord(source.bankAccountData)?source.bankAccountData:{}; const accounts=Array.isArray(bankRoot.accounts)?records(bankRoot.accounts):array(source,'bankAccountDetails')??[]; draft.bankAccounts=accounts.map((item,index):BankAccount=>({id:itemId('bank',index,item),bankName:text(item.bankName),accountNumber:text(item.accountNumber),ifscCode:text(item.ifscCode),accountType:enumValue(item.accountType,['SB','CA','CC','OD','NRO','OTH'] as const,text(item.accountType)==='SAVINGS'?'SB':text(item.accountType)==='CURRENT'?'CA':'OTH'),useForRefund:bool(item.useForRefund,index===0)}));
  const verification=isRecord(source.verification)?source.verification:{}; draft.verification={capacity:enumValue(verification.capacity,['SELF','REPRESENTATIVE'] as const,'SELF'),place:text(verification.place),date:text(verification.date)||null,declarationAccepted:bool(verification.declarationAccepted)}; const provenance=array(source,'provenance')??array(source,'importProvenance')??[]; draft.provenance=provenance.map((item)=>({source:enumValue(item.source,['MANUAL','FORM16','AIS','TIS','26AS','ITD_PREFILL','LEGACY'] as const,'LEGACY'),importedAt:text(item.importedAt)||null,reference:text(item.reference)})); if(!draft.provenance.length&&Object.keys(source).length)draft.provenance.push({source:'LEGACY',importedAt:null,reference:''});
  const unknownFields=Object.fromEntries(Object.entries(source).filter(([key])=>!known.has(key))); if(Object.keys(unknownFields).length)draft.compatibility={source:'legacy-flat-v1',unknownFields}; return draft;
}
