import type { ReturnDraft } from './types';
type JsonRecord = Record<string, unknown>;
/** Converts a normalized draft to the temporary flat backend contract. @deprecated Remove when backend accepts schema v1. */
export function serializeReturnDraftToLegacy(draft: ReturnDraft): JsonRecord {
  const loanRoot: JsonRecord = { section80E:{loans:[]},section80EE:{loans:[]},section80EEA:{loans:[],stampDutyValue:draft.deductions.loans.section80EEAStampDutyValue},section80EEB:{loans:[]} };
  for(const loan of draft.deductions.loans.loans){const group=loanRoot[`section${loan.section}`] as {loans:unknown[]};group.loans.push({id:loan.id,loanTakenFrom:loan.loanTakenFrom,bankOrInstnName:loan.lenderName,lenderPAN:loan.lenderPAN,loanAccNo:loan.loanAccountNo,dateOfLoan:loan.dateOfLoan,totalLoanAmt:loan.totalLoanAmount,loanOutstandingAmt:loan.outstandingAmount,interestAmount:loan.interestAmount,firstTimeBuyerEligible:loan.firstTimeBuyerEligible,vehicleRegNo:loan.vehicleRegNo});}
  const compatibilityFields: JsonRecord = draft.compatibility
    ? structuredClone(draft.compatibility.unknownFields)
    : {};
  const payload: JsonRecord={...compatibilityFields,assessmentYear:draft.assessmentYear,itrForm:draft.form,form:draft.form,regime:draft.regime,taxRegime:draft.regime,...draft.personal,dob:draft.personal.dateOfBirth,filing:{...draft.filing},...draft.filing,
    employerEntries:draft.employers.map((x)=>({...x})),housePropertyEntries:draft.houseProperties.map((x)=>({...x,coOwners:x.coOwners.map((y,index)=>({...y,coOwnerSNo:index+1})),tenantDetails:x.tenantDetails.map((y,index)=>({...y,tenantSNo:index+1})),tenantName:x.tenantDetails[0]?.name??x.tenantName,tenantPAN:x.tenantDetails[0]?.pan??x.tenantPAN,tenantAadhaar:x.tenantDetails[0]?.aadhaar??x.tenantAadhaar,homeLoans:x.homeLoans.map((y)=>({...y}))})),businessEntries:draft.businesses.map((x)=>({...x,gstinTurnovers:x.gstinTurnovers.map((y)=>({...y})),financialParticulars:{...x.financialParticulars},...(x.scheme==='44AE'?{vehicles:x.vehicles.map((y)=>({...y}))}:{})})),
    interestEntries:draft.otherSources.interest.map((x)=>({...x,itdTag:x.kind})),bankInterestEntries:draft.otherSources.interest.map((x)=>({...x,itdTag:x.kind})),dividendEntries:draft.otherSources.dividends.map((x)=>({...x})),familyPensionEntry:{...draft.otherSources.familyPension},familyPension:draft.otherSources.familyPension.grossAmount,winningsEntries:draft.otherSources.winnings.map((x)=>({...x})),giftEntries:draft.otherSources.gifts.map((x)=>({...x})),exemptIncomeEntries:draft.exemptIncome.map((x)=>({...x})),
    section80C:{investments:draft.deductions.section80C.map((x)=>({...x}))},section80D:{selfSeniorCitizen:draft.deductions.section80D.selfSeniorCitizen,parentsSeniorCitizen:draft.deductions.section80D.parentsSeniorCitizen,selfFamily:{...draft.deductions.section80D.selfFamily,policies:draft.deductions.section80D.selfFamily.policies.map((x)=>({...x}))},selfFamilySenior:{...draft.deductions.section80D.selfFamilySenior,policies:draft.deductions.section80D.selfFamilySenior.policies.map((x)=>({...x}))},parents:{...draft.deductions.section80D.parents,policies:draft.deductions.section80D.parents.policies.map((x)=>({...x}))},parentsSenior:{...draft.deductions.section80D.parentsSenior,policies:draft.deductions.section80D.parentsSenior.policies.map((x)=>({...x}))}},donationEntries:draft.deductions.section80G.map((x)=>({...x})),deductionLoans:loanRoot,
    tdsEntries:draft.taxes.tds.map((x)=>({...x,incomeAmount:x.grossAmount,tdsDeducted:x.taxDeducted})),tcsEntries:draft.taxes.tcs.map((x)=>({...x,tcsCollected:x.taxCollected})),advanceTaxEntries:draft.taxes.challans.filter((x)=>x.kind==='ADVANCE_TAX').map((x)=>({id:x.id,bsrCode:x.bsrCode,depositDate:x.depositDate,challanSerialNo:x.challanSerialNo,amount:x.amount,cin:x.cin})),selfAssessmentTaxEntries:draft.taxes.challans.filter((x)=>x.kind==='SELF_ASSESSMENT').map((x)=>({id:x.id,bsrCode:x.bsrCode,depositDate:x.depositDate,challanSerialNo:x.challanSerialNo,amount:x.amount,cin:x.cin})),bankAccountData:{accounts:draft.bankAccounts.map((x)=>({...x}))},bankAccountDetails:draft.bankAccounts.map((x)=>({...x})),verification:{...draft.verification},provenance:draft.provenance.map((x)=>({...x})),
    basic:0,da:0,hra:0,bonus:0,allowances:0,grossRent:0,munTax:0,homeLoanInt:0,interestSB:0,interestFD:0,interestRD:0,dividends:0,s80G:0,tdsS192:0,tds194A:0,tdsOther:0,adv15Jun:0,adv15Sep:0,adv15Dec:0,adv15Mar:0,selfTax:0};
  return payload;
}
